/** Exact runtime asset, isolated controls and responsive input regression; no live writes. */
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { pathToFileURL } from 'node:url';

const pw = await import(process.env.HIDI_PLAYWRIGHT_MODULE ? pathToFileURL(process.env.HIDI_PLAYWRIGHT_MODULE).href : 'playwright');
const runtime = process.env.HIDI_CANDIDATE_RUNTIME;
const root = runtime ? join(runtime, 'button-states') : resolve('deploy/button-states');
const css = await readFile(process.env.HIDI_BUTTON_CSS || join(root, 'buttons.css'));
const script = await readFile(process.env.HIDI_BUTTON_SCRIPT || join(root, 'buttons.js'));
const paper = 'rgb(251, 246, 242)', brown = 'rgb(89, 29, 32)', ivory = 'rgb(255, 248, 239)', green = 'rgb(37, 211, 102)', greenInk = 'rgb(5, 66, 37)';
const ordinary = [
  ['native', '<button type="button">Add to bag</button>'],
  ['submit', '<button type="submit">Pay securely</button>'],
  ['input-submit', '<input type="submit" value="Subscribe">'],
  ['input-button', '<input type="button" value="Continue">'],
  ['role-button', '<div role="button" tabindex="0">Continue</div>'],
  ['button-link', '<a href="#fixture" class="button button--gold">Explore our range</a>'],
  ['dark-link', '<a href="#fixture" class="button-dark">Continue shopping</a>'],
  ['hashed-button-link', '<a href="#fixture" class="wallet_button_h42">Sign in to view rewards</a>'],
  ['cart-link', '<a href="#fixture" class="cart-checkout-button">Checkout</a>'],
  ['header-button', '<header class="site-header"><button type="button" aria-label="Open navigation">Menu</button></header>'],
  ['false-class', '<button type="button" class="inactive interactive activeFilters is-inactive not-active">Unselected</button>'],
];
const markup = ordinary.map(([id, html]) => `<div class="fixture-row" id="wrap-${id}">${html.replace(/<(button|input|a|div)\b/, `<$1 id="${id}"`)}</div>`).join('');
const html = route => `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
*{box-sizing:border-box} :root{--hidi-page-bg:#fbf6f2;--paper:#fbf6f2}body{margin:0;padding:16px;background:#fbf6f2;color:#342a24;font-family:Arial,sans-serif}main{max-width:700px;margin:auto}h1{font-size:20px}.fixture-row{margin:6px 0;display:flex;gap:8px;flex-wrap:wrap}button,input[type=button],input[type=submit],[role=button],a.button,a.button-dark,a.cart-checkout-button,a.wallet_button_h42{min-height:44px;padding:10px 13px;border:1px solid #591d20;border-radius:5px;background:#591d20;color:#fff8ef;font:inherit;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center;gap:6px}button:disabled{opacity:.45;cursor:not-allowed}.site-header{padding:8px;background:#591d20}.site-header button{color:#fff8ef}.selected,.active,[aria-pressed=true]{background:#222}button strong,button small,label small{color:#74635c}label.choice{min-height:48px;display:flex;gap:8px;padding:8px;border:1px solid #ddd;background:#fff}.choice span{display:grid}.choice small{font-size:12px}.actions{display:flex;gap:8px;flex-wrap:wrap}.actions button{max-width:100%}.actions button span{display:grid;min-width:0}.actions .product-contact-actions_whatsapp_h42,.product-contact-actions_continueButton_h42{background:#25d366;color:#fff;border-color:#25d366}.actions .product-contact-actions_whatsapp_h42 small{color:#f5fff8}.plain-link{color:#234;background:transparent;border:0}.admin-nav{background:#591d20;padding:8px}.admin-workspace_navLink_h42{display:block;padding:8px;color:#fff8ef;background:transparent}.presets{display:grid;gap:6px}textarea,input[type=text]{max-width:100%}button:focus-visible{outline:3px solid #d5a24d;outline-offset:3px}@media(prefers-reduced-motion:reduce){*{transition:none!important}}
</style><link rel="stylesheet" href="/buttons.css"><style>
/* Exact retained runtime overrides, intentionally loaded after the theme. */
#reviews details summary{background:#591d20!important;border-color:#591d20!important;color:#fff8ef!important}
#reviews details summary:hover{background:#69282a!important}
</style></head><body><main><h1>Isolated button state fixture</h1>${markup}
<div class="fixture-row"><button id="toggle" aria-pressed="false" onclick="this.setAttribute('aria-pressed',this.getAttribute('aria-pressed')==='true'?'false':'true')">Size M</button><button id="peer" aria-pressed="false">Size L</button></div>
<div class="pdp-gallery"><button id="gallery-button" type="button" class="pdp-image product-art"><img width="36" height="44" alt="Product photo" src="data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%2736%27 height=%2744%27/%3E"></button></div><button id="color-swatch" aria-pressed="false"><i style="display:block;background:#047bad;width:12px;height:12px"></i>Ocean</button>
<div class="fixture-row"><button id="aria-selected" role="tab" aria-selected="false">Size guide cm</button><button id="aria-expanded" aria-expanded="false">Filter &amp; Sort</button><button id="class-selected">Packing order</button><button id="class-active">Adjustment</button><button id="hash-active">Exchange</button><button id="hash-size-active">Quick add XL</button></div>
<div class="fixture-row"><button id="badge-button" aria-expanded="false"><span>Filter</span><span id="badge" class="collection-browser_filterCount_h42" style="background:#591d20;color:white;border-radius:999px;padding:2px 6px">2</span></button><button id="modern-badge-button" aria-pressed="false"><span>Bag</span><span id="modern-badge" class="header-icons-module__bHtKh9__count" style="background:#591d20;color:white;border-radius:999px;padding:2px 6px">3</span></button></div>
<div class="fixture-row"><button id="disabled" disabled aria-pressed="false">Unavailable size</button><fieldset disabled><button id="fieldset-disabled">Updating…</button></fieldset><a id="aria-disabled" class="button" href="#never" aria-disabled="true">Unavailable action</a><button id="disabled-selected" disabled aria-pressed="true">Previously selected unavailable size</button></div>
<section class="checkout-payment-methods"><label class="choice" id="online"><input type="radio" name="payment" value="online" checked><span><strong>Pay online</strong><small>UPI, cards and rewards</small></span></label><label class="choice" id="cod"><input type="radio" name="payment" value="cod"><span><strong>Cash on delivery</strong><small>Pay when your order arrives</small></span></label></section>
<label class="choice" id="checkbox-label"><input type="checkbox"><span><strong>Fixture size filter</strong><small>Choose this size</small></span></label><details><summary id="summary-control">Shipping &amp; Returns</summary><p>Shipping information</p></details>
<section id="reviews"><details><summary id="review-summary">How to write a review</summary><p>Sign in to review this product.</p></details></section>
<div class="actions"><button id="whatsapp" class="product-contact-actions_whatsapp_h42" type="button" aria-haspopup="dialog"><svg width="18" height="18" aria-hidden="true"></svg><span><strong>Order on WhatsApp</strong><small>Review your selection</small></span></button><button id="whatsapp-continue" class="product-contact-actions_continueButton_h42" type="button">Continue on WhatsApp</button></div>
<button id="unrelated-whatsapp">WhatsApp preferences</button><a class="plain-link" id="plain" href="#fixture">Privacy policy</a><input type="text" id="plain-input" value="Product name"><textarea id="plain-textarea">Product details</textarea>
<nav class="admin-nav" aria-label="Admin navigation"><a id="nav-current" class="admin-workspace_navLink_h42 admin-workspace_navActive_h42" href="/admin/products" aria-current="page">Products</a><a id="nav-other" class="admin-workspace_navLink_h42" href="/admin/orders">Orders</a></nav>
<div id="late-root"></div><p id="fixture">${route}</p></main><script>document.addEventListener('submit',e=>e.preventDefault());document.addEventListener('click',e=>{if(e.target.closest('a'))e.preventDefault();});</script><script src="/buttons.js"></script></body></html>`;
const server = createServer((req, res) => {
  const path = new URL(req.url, 'http://fixture.test').pathname;
  if (path === '/buttons.css') { res.writeHead(200, { 'content-type': 'text/css' }); return res.end(css); }
  if (path === '/buttons.js') { res.writeHead(200, { 'content-type': 'text/javascript' }); return res.end(script); }
  res.writeHead(200, { 'content-type': 'text/html' }); res.end(html(path));
});
await new Promise(done => server.listen(0, '127.0.0.1', done));
const base = `http://127.0.0.1:${server.address().port}`;
const output = resolve(process.env.HIDI_BUTTON_OUTPUT || 'test-results/button-states'); await mkdir(output, { recursive: true });
const results = []; let activeBrowser, checks = 0;
async function palette(page, id, selected = false, exception = false, bodyColor = paper) {
  const element = page.locator('#' + id);
  const colors = await element.evaluate(el => {const s=getComputedStyle(el);return {background:s.backgroundColor,color:s.color,border:s.borderTopColor,width:parseFloat(s.borderTopWidth),style:s.borderTopStyle};});
  assert.equal(colors.background, exception ? green : selected ? brown : bodyColor, id + ' background');
  assert.equal(colors.color, exception ? greenInk : selected ? ivory : brown, id + ' text');
  assert.equal(colors.border, exception ? green : brown, id + ' border');
  assert(colors.width >= 1 && colors.style !== 'none', id + ' visible border'); checks += 4;
}
async function change(page, id, attribute, value) { await page.locator('#' + id).evaluate((el, change) => change.value === null ? el.removeAttribute(change.attribute) : el.setAttribute(change.attribute, change.value), {attribute,value}); await page.waitForTimeout(40); }
try {
  for (const engine of (process.env.HIDI_BROWSER_ENGINES || 'chromium,firefox,webkit').split(',')) {
    activeBrowser = await pw[engine].launch({ headless: true, ...(engine === 'firefox' ? { env: {...process.env,MOZ_DISABLE_CONTENT_SANDBOX:'1'} } : {}), ...(engine === 'webkit' && process.env.HIDI_WEBKIT_EXECUTABLE ? { executablePath: process.env.HIDI_WEBKIT_EXECUTABLE } : {}) });
    for (const viewport of [{width:320,height:568},{width:390,height:844},{width:844,height:390},{width:1440,height:900}]) {
      const context = await activeBrowser.newContext({viewport,hasTouch:viewport.width<1100,reducedMotion:'reduce'}), page=await context.newPage();
      page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',error=>errors.push(error.message));
      const scenario = async (id, work) => {const started=Date.now();try{await work();results.push({engine,...viewport,id,status:'PASS',durationMs:Date.now()-started});}catch(error){results.push({engine,...viewport,id,status:'FAIL',error:error.stack});await page.screenshot({path:join(output,`${engine}-${viewport.width}-${id}-failure.png`),fullPage:true}).catch(()=>{});throw error;}};
      await page.goto(base + '/products/isolated-fixture');
      await page.waitForFunction(() => getComputedStyle(document.querySelector('#native')).backgroundColor === 'rgb(251, 246, 242)');
      await scenario('default-all-surfaces',async()=>{for(const [id] of ordinary)await palette(page,id);await palette(page,'toggle');await palette(page,'peer');await palette(page,'aria-expanded');});
      await scenario('pressed-toggle-and-peer',async()=>{await page.locator('#toggle').click();await page.mouse.move(1,1);await page.locator('#toggle').evaluate(el=>el.blur());await palette(page,'toggle',true);await palette(page,'peer');await page.locator('#toggle').click();await page.mouse.move(1,1);await page.locator('#toggle').evaluate(el=>el.blur());await palette(page,'toggle');assert.equal(await page.locator('#toggle').getAttribute('aria-pressed'),'false');checks++;});
      await scenario('semantic-selected-state',async()=>{for(const [id,attr] of [['aria-selected','aria-selected'],['aria-expanded','aria-expanded']]){await change(page,id,attr,'true');await palette(page,id,true);await change(page,id,attr,'false');await palette(page,id);}await palette(page,'peer');});
      await scenario('legacy-and-css-module-selected-state',async()=>{for(const [id,cls] of [['class-selected','order selected'],['class-active','active'],['class-active','is-active'],['class-selected','is-selected'],['hash-active','return-exchange-request_choiceActive_h42'],['hash-size-active','product-card_mobileSheetSizeActive_h42'],['hash-active','return-exchange-request-module__bHtKh9__choiceActive'],['class-active','admin-inventory-module__qHtKh9__active']]){await change(page,id,'class',cls);await palette(page,id,true);await change(page,id,'class','');await palette(page,id);}await palette(page,'false-class');await palette(page,'nav-current',true);await palette(page,'nav-other');});
      await scenario('disabled-selection-and-input-semantics',async()=>{for(const id of ['disabled','fieldset-disabled','aria-disabled'])await palette(page,id);await palette(page,'disabled-selected',true);await page.locator('#disabled').evaluate(el=>el.click());assert.equal(await page.locator('#disabled').getAttribute('aria-pressed'),'false');assert(await page.locator('#disabled').isDisabled());assert(await page.locator('#fieldset-disabled').isDisabled());assert.equal(await page.locator('#disabled').evaluate(el=>getComputedStyle(el).cursor),'not-allowed');checks+=4;});
      await scenario('checked-payment-choices-and-readable-copy',async()=>{await palette(page,'online',true);await palette(page,'cod');await page.locator('#cod input').check();await palette(page,'online');await palette(page,'cod',true);for(const id of ['online','cod']){const colors=await page.locator('#'+id+' span>*').evaluateAll(els=>els.map(el=>getComputedStyle(el).color));assert(colors.every(color=>color===(id==='cod'?ivory:brown)),id+' descendant text follows selection');checks++;}assert(await page.locator('#cod input').isChecked());checks++;});
      await scenario('native-checkbox-filter-state',async()=>{await palette(page,'checkbox-label');await page.locator('#checkbox-label input').check();await palette(page,'checkbox-label',true);assert.equal(await page.locator('#checkbox-label small').evaluate(el=>getComputedStyle(el).color),ivory);await page.locator('#checkbox-label input').uncheck();await palette(page,'checkbox-label');checks++;});
      await scenario('count-badges-preserve-contrast-in-both-states',async()=>{for(const [button,badge,attribute] of [['badge-button','badge','aria-expanded'],['modern-badge-button','modern-badge','aria-pressed']]){await palette(page,button);let color=await page.locator('#'+badge).evaluate(el=>({background:getComputedStyle(el).backgroundColor,color:getComputedStyle(el).color}));assert.deepEqual(color,{background:brown,color:paper});await change(page,button,attribute,'true');await palette(page,button,true);color=await page.locator('#'+badge).evaluate(el=>({background:getComputedStyle(el).backgroundColor,color:getComputedStyle(el).color}));assert.deepEqual(color,{background:ivory,color:brown});await change(page,button,attribute,'false');checks+=4;}});
      await scenario('disclosure-open-and-close-state',async()=>{await palette(page,'summary-control');await page.locator('#summary-control').click();await palette(page,'summary-control',true);await page.locator('#summary-control').click();await page.locator('#summary-control').evaluate(el=>el.blur());await palette(page,'summary-control');});
      await scenario('retained-review-disclosure-default-hover-open-and-keyboard',async()=>{const summary=page.locator('#review-summary');await palette(page,'review-summary');await summary.hover();await palette(page,'review-summary');await summary.click();await palette(page,'review-summary',true);await summary.click();await summary.evaluate(el=>el.blur());await page.mouse.move(1,1);await palette(page,'review-summary');await summary.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');assert(await summary.evaluate(el=>document.activeElement===el));await palette(page,'review-summary',true);await summary.evaluate(el=>el.blur());checks++;});
      await scenario('whatsapp-theme-kept-only-for-order-actions',async()=>{for(const id of ['whatsapp','whatsapp-continue']){await palette(page,id,false,true);await change(page,id,'aria-pressed','true');await palette(page,id,true,true);await change(page,id,'aria-pressed',null);await change(page,id,'disabled','');await palette(page,id,false,true);await change(page,id,'disabled',null);}await palette(page,'unrelated-whatsapp');const descendant=await page.locator('#whatsapp strong').evaluate(el=>getComputedStyle(el).color);assert.equal(descendant,greenInk);checks++;});
      await scenario('pointer-press-is-temporary',async()=>{const target=page.locator('#native');await target.scrollIntoViewIfNeeded();const box=await target.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await palette(page,'native');await page.mouse.down();await palette(page,'native',true);await page.mouse.up();await page.mouse.move(1,1);await target.evaluate(el=>el.blur());await palette(page,'native');});
      await scenario('keyboard-focus-visible-and-activation',async()=>{await page.evaluate(()=>document.activeElement?.blur());await page.locator('#toggle').focus();await page.keyboard.press('Tab');assert(await page.locator('#peer').evaluate(el=>document.activeElement===el));assert(await page.locator('#peer').evaluate(el=>{const s=getComputedStyle(el);return s.outlineStyle!=='none'&&parseFloat(s.outlineWidth)>=2;}),'Keyboard focus remains visible');await palette(page,'peer',true);checks+=2;await page.locator('#toggle').focus();await page.keyboard.press('Space');await page.mouse.move(1,1);await page.locator('#toggle').evaluate(el=>el.blur());await palette(page,'toggle',true);});
      await scenario('late-react-hydration-and-route-change',async()=>{await page.evaluate(()=>{document.querySelector('#late-root').innerHTML='<button id="late" class="product-card_addButton_h42" aria-pressed="false">Added later</button>';history.pushState(null,'','/collections/all');dispatchEvent(new PopStateEvent('popstate'));});await page.waitForTimeout(80);await palette(page,'late');await change(page,'late','aria-pressed','true');await palette(page,'late',true);await page.evaluate(()=>document.querySelector('#late').outerHTML='<button id="late" aria-pressed="false">Hydrated replacement</button>');await page.waitForTimeout(80);await palette(page,'late');});
      await scenario('root-theme-recovers-after-hydration-with-selection-preserved',async()=>{await change(page,'toggle','aria-pressed','true');await page.evaluate(()=>{document.documentElement.removeAttribute('data-hidi-button-theme');document.documentElement.style.removeProperty('--hidi-button-body');});await page.waitForFunction(()=>document.documentElement.getAttribute('data-hidi-button-theme')==='site');assert.equal(await page.locator('#toggle').getAttribute('aria-pressed'),'true');await palette(page,'toggle',true);await palette(page,'peer');assert.equal(await page.locator('#plain-input').inputValue(),'Product name');await change(page,'toggle','aria-pressed','false');await palette(page,'toggle');checks+=2;});
      await scenario('unrelated-fields-links-images-and-swatch-preserved',async()=>{assert.equal(await page.locator('#plain').evaluate(el=>getComputedStyle(el).backgroundColor),'rgba(0, 0, 0, 0)');assert.equal(await page.locator('#plain-input').inputValue(),'Product name');assert.equal(await page.locator('#plain-textarea').inputValue(),'Product details');assert.equal(await page.locator('#gallery-button').evaluate(el=>getComputedStyle(el).backgroundColor),brown,'Image hit areas preserve photography styling');await palette(page,'color-swatch');assert.equal(await page.locator('#color-swatch i').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(4, 123, 173)');await change(page,'color-swatch','aria-pressed','true');await palette(page,'color-swatch',true);assert.equal(await page.locator('#color-swatch i').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(4, 123, 173)');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No responsive horizontal overflow');assert.deepEqual(errors,[]);checks+=8;await page.screenshot({path:join(output,`${engine}-${viewport.width}-states.png`),fullPage:true});});
      await scenario('admin-controls-and-route-transitions-use-same-states',async()=>{await page.evaluate(()=>{history.pushState(null,'','/admin/products');dispatchEvent(new PopStateEvent('popstate'));});await page.waitForTimeout(80);assert.equal(await page.locator('html').getAttribute('data-hidi-button-theme'),'site');await palette(page,'native');await palette(page,'nav-current',true);await palette(page,'nav-other');await page.goto(base+'/admin/products');await page.waitForTimeout(80);assert.equal(await page.locator('html').getAttribute('data-hidi-button-theme'),'site');await palette(page,'native');await page.evaluate(()=>{history.pushState(null,'','/cart');dispatchEvent(new PopStateEvent('popstate'));});await page.waitForTimeout(80);await palette(page,'native');checks+=2;});
      await scenario('standalone-admin-body-palette-is-respected',async()=>{await page.evaluate(()=>{document.body.style.backgroundColor='#f7f1eb';dispatchEvent(new Event('pageshow'));});await page.waitForTimeout(40);await palette(page,'native',false,false,'rgb(247, 241, 235)');await palette(page,'toggle',false,false,'rgb(247, 241, 235)');await change(page,'toggle','aria-pressed','true');await palette(page,'toggle',true);});
      await context.close();console.log(`PASS ${engine} ${viewport.width}: default, selected, disabled, pointer, keyboard, payment, WhatsApp and hydration states`);
    }
    await activeBrowser.close();activeBrowser=null;
  }
} finally { await activeBrowser?.close().catch(()=>{});server.closeAllConnections();await new Promise(done=>server.close(done));await writeFile(join(output,'report.json'),JSON.stringify({scope:'Exact source or candidate runtime assets; isolated fixture; no live writes',checks,results},null,2)); }
assert.equal(results.filter(result=>result.status==='FAIL').length,0);console.log(`${results.length} button-state scenarios and ${checks} assertions passed.`);
