// Offline SSR/parsed-DOM and CSS contracts. NOT browser E2E.
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { createRequire } = require('node:module');
const webRoot = path.resolve(__dirname, '../apps/web');
const webRequire = createRequire(path.join(webRoot, 'package.json'));
const nextRequire = createRequire(webRequire.resolve('next/package.json'));
const React = webRequire('react');
const { renderToStaticMarkup } = webRequire('react-dom/server');
const ts = webRequire('typescript');
const { parse } = nextRequire('next/dist/compiled/node-html-parser');
const postcss = nextRequire('postcss');
const source = relative => fs.readFileSync(path.join(webRoot, relative), 'utf8');
const interop = value => ({ __esModule: true, default: value });
const matches = (text, patterns) => { for (const pattern of patterns) assert.match(text, pattern); };
function harness({ products = [], bestSellers = [], whatsappNumber = '' } = {}) {
  const cache = new Map();
  const imports = {
    react: React, 'react/jsx-runtime': webRequire('react/jsx-runtime'), 'lucide-react': webRequire('lucide-react'),
    'next/link': interop(({ children, ...props }) => React.createElement('a', props, children)),
    'next/image': interop(({ fill, priority, ...props }) => React.createElement('img', props)),
    '@/components/editorial-product-card': { EditorialProductCard: ({ product }) => React.createElement('article', { 'data-qa-product': product.slug }, product.name) },
    '@/components/product-card': { ProductCard: ({ product }) => React.createElement('article', { 'data-qa-product': product.slug }, product.name) },
    '@/lib/api': {
      getProducts: async () => products, getBestSellers: async () => bestSellers,
      getFeaturedProducts: async (limit = 6) => { const ranked = bestSellers.length ? [...bestSellers, ...products.filter(product => !bestSellers.some(best => best.id === product.id))] : products; return ranked.slice(0, limit); },
      formatPaise: value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value / 100),
    },
  };
  function load(relative) {
    if (cache.has(relative)) return cache.get(relative);
    const module = { exports: {} }; cache.set(relative, module.exports);
    const compiled = ts.transpileModule(source(relative), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, jsx: ts.JsxEmit.ReactJSX, esModuleInterop: true } }).outputText;
    function resolveImport(name) {
      if (Object.hasOwn(imports, name)) return imports[name];
      const target = name.startsWith('@/') ? name.slice(2) : path.join(path.dirname(relative), name);
      if (name.endsWith('.module.css')) { const css = postcss.parse(source(target)), classes = {}; css.walkRules(rule => { for (const match of rule.selector.matchAll(/\.([A-Za-z_][\w-]*)/g)) classes[match[1]] = match[1]; }); return interop(classes); }
      if (name.startsWith('@/') || name.startsWith('.')) { const found = [target, target + '.tsx', target + '.ts'].find(candidate => fs.existsSync(path.join(webRoot, candidate))); if (found) return load(found); }
      throw new Error(`Unexpected dependency in offline storefront QA: ${name}`);
    }
    vm.runInNewContext(compiled, { module, exports: module.exports, require: resolveImport, process: { env: { NEXT_PUBLIC_HIDI_WHATSAPP_NUMBER: whatsappNumber } }, URL, URLSearchParams, AbortController, fetch() { throw new Error('Network calls are forbidden in storefront SSR QA'); } }, { filename: relative });
    return module.exports;
  }
  return {
    async homepage() { return parse(renderToStaticMarkup(await load('app/page.tsx').default())); },
    reviews(data) { return parse(renderToStaticMarkup(React.createElement(load('components/product-reviews.tsx').ProductReviews, { data }))); },
    contact(product) { return parse(renderToStaticMarkup(React.createElement(load('components/product-contact-actions.tsx').ProductContactActions, { product }))); },
  };
}
function product(index, overrides = {}) { return { id: `p${index}`, slug: `style-${index}`, name: `HIDI style ${index}`, minPricePaise: 149900, maxPricePaise: 149900, inStock: true, images: [{ id: `image-${index}`, url: `/qa/style-${index}.jpg`, alt: `Garment ${index}`, position: 0 }], collections: [], variants: [{ id: `v${index}-m`, sku: `QA-${index}-M`, color: 'Sage', size: 'M', pricePaise: 149900, mrpPaise: 179900, available: 4 }, { id: `v${index}-l`, sku: `QA-${index}-L`, color: 'Sage', size: 'L', pricePaise: 149900, mrpPaise: 179900, available: 0 }], ...overrides }; }
const catalogue = Array.from({ length: 10 }, (_, index) => product(index));
const emptyReviews = { averageRating: 0, reviewCount: 0, reviews: [] };
const review = { id: 'review-1', rating: 4, title: 'A comfortable fit', body: 'Lovely fabric for a workday.', reviewerName: 'QA Customer', verifiedPurchase: true, createdAt: '2026-09-01T00:00:00Z' };
function byId(root, id) { return root.querySelectorAll('[id]').find(element => element.getAttribute('id') === id); }
function assertReferencesResolve(root) { const ids = root.querySelectorAll('[id]').map(element => element.getAttribute('id')); assert.equal(new Set(ids).size, ids.length); for (const attribute of ['aria-labelledby', 'aria-describedby', 'aria-controls', 'for']) for (const element of root.querySelectorAll(`[${attribute}]`)) for (const id of element.getAttribute(attribute).split(/\s+/)) assert.ok(byId(root, id), `${attribute} references missing element ${id}`); }
function cssRule(relative, selector, media = null) { let declarations = null; postcss.parse(source(relative)).walkRules(rule => { if (!rule.selector.split(',').map(value => value.trim()).includes(selector)) return; let ancestor = rule.parent; while (ancestor && !(ancestor.type === 'atrule' && ancestor.name === 'media')) ancestor = ancestor.parent; if ((ancestor?.params ?? null) !== media) return; declarations ??= {}; rule.walkDecls(declaration => { declarations[declaration.prop] = declaration.value; }); }); assert.ok(declarations, `Missing CSS rule ${selector} in ${relative} (${media ?? 'base'})`); return declarations; }

test('social proof uses only real published review evidence', () => {
  matches(source('components/product-reviews.tsx'), [/ratingDistribution/, /verifiedReviewCount/, /Verified purchase means the review is matched to a delivered HIDI order/, /Ratings include all published customer reviews for this style/]);
  matches(source('components/product-card.tsx'), [/!!product\.reviewCount && product\.reviewCount > 0/, /href=\{\`\$\{href\}#reviews\`\}/, /product\.averageRating\.toFixed\(1\)/]);
  matches(fs.readFileSync(path.resolve(__dirname, '../apps/api/src/products/products.service.ts'), 'utf8'), [/productReview\.groupBy/, /withReviewSummaries/, /published: true/]);
  const code = fs.readFileSync(path.resolve(__dirname, '../apps/api/src/admin/review-followup.service.ts'), 'utf8'); matches(code, [/shipments:/, /deliveredAt: \{ lte: cutoff \}/]); assert.doesNotMatch(code, /createdAt: \{ lte: cutoff \}/);
});
test('WCAG foundation keeps keyboard focus visible and modal overlays contained', () => {
  matches(source('components/site-shell.tsx'), [/className="skip-link"/, /id="main-content"/, /tabIndex=\{-1\}/]);
  matches(source('lib/focus-management.ts'), [/focusableElements/, /trapFocus/, /event\.key !== "Tab"/]);
  matches(source('components/header.tsx'), [/role="dialog"/, /aria-modal="true"/, /trapFocus\(event, menuPanelRef\.current\)/, /aria-current=\{pathname === href \? "page"/]);
  matches(source('components/header-search.tsx'), [/role="dialog"/, /aria-modal="true"/, /trapFocus\(event, panelRef\.current\)/]);
  const collection = source('components/collection-browser.tsx'); matches(collection, [/\{mobileOpen && sidebar\}/, /trapFocus\(event, filterDialogRef\.current\)/]); assert.doesNotMatch(collection, /aria-hidden=\{!mobileOpen\}/);
  assert.match(source('components/product-card.tsx'), /trapFocus\(event, mobileSheetRef\.current\)/); assert.match(source('components/product-gallery.tsx'), /trapFocus\(event, dialogRef\.current\)/);
  matches(source('app/globals.css'), [/:where\(a, button, input, select, textarea, summary, \[tabindex\]\):focus-visible/, /@media \(prefers-reduced-motion: reduce\)/]);
});
test('forms and utility controls expose assistive status and labels', () => {
  matches(source('components/newsletter-signup.tsx'), [/aria-describedby="newsletter-status"/, /role=\{error \? "alert" : "status"\}/]); assert.match(source('components/header-search.tsx'), /role="status"/); assert.match(source('app/products/[slug]/page.tsx'), /<DeliveryCheck/);
  matches(source('components/delivery-check.tsx'), [/aria-label="Delivery PIN code"/, /aria-label="Check delivery PIN code"/, /role="status"/]); matches(source('components/collection-browser.module.css'), [/min-height: 44px/, /width: 18px/, /height: 18px/]);
});
test('SEO foundation exposes canonical metadata, sitemap and crawl controls', () => {
  matches(source('app/layout.tsx'), [/metadataBase: site/, /summary_large_image/, /"@type": "Organization"/, /"@type": "WebSite"/, /GOOGLE_SITE_VERIFICATION/, /NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION/, /<AnalyticsTags/]); assert.match(source('app/page.tsx'), /alternates: \{ canonical: "\/" \}/);
  const robots = source('app/robots.ts'); matches(robots, [/sitemap: absoluteUrl\("\/sitemap\.xml"\)/, /"\/api"/, /"\/admin"/]); assert.doesNotMatch(robots, /"\/checkout"/);
  matches(source('app/sitemap.ts'), [/\/collections\/casual-wear/, /\/collections\/work-wear/, /\/collections\/occasional-wear/, /\/collections\/ananyas-pick/, /\/about/, /\/shipping/, /\/returns/, /\/products\/\$\{encodeURIComponent\(product\.slug\)\}/]);
  const site = source('lib/site-url.ts'); matches(site, [/process\.env\.HIDI_PRIMARY_DOMAIN/, /process\.env\.SITE_URL/, /VERCEL_PROJECT_PRODUCTION_URL/]); assert.ok(site.includes('replace(/</g, "\\\\u003c")'), 'JSON-LD must escape less-than characters');
});
test('analytics and browser security hardening stay environment gated', () => {
  matches(source('components/analytics-tags.tsx'), [/NEXT_PUBLIC_GA_MEASUREMENT_ID|gaMeasurementId/, /googletagmanager\.com\/gtag\/js/, /connect\.facebook\.net\/en_US\/fbevents\.js/, /firstPageView/, /PageView/]);
  const layout = source('app/layout.tsx'); matches(layout, [/isSearchIndexingEnabled\(\)/, /NEXT_PUBLIC_META_PIXEL_ID/, /NEXT_PUBLIC_FACEBOOK_PIXEL_ID/]);
  const nextConfig = source('next.config.ts'); matches(nextConfig, [/X-Content-Type-Options/, /X-Frame-Options/, /Referrer-Policy/, /Permissions-Policy/, /Cross-Origin-Opener-Policy/, /Strict-Transport-Security/]); assert.doesNotMatch(nextConfig, /Content-Security-Policy/);
});
test('product and collection pages publish search metadata and structured data', () => {
  matches(source('app/products/[slug]/page.tsx'), [/generateMetadata/, /alternates: \{ canonical \}/, /"@type": "Product"/, /offers: productOffers\(product, canonicalUrl\)/, /"@type": "BreadcrumbList"/, /aggregateRating/, /cache\(getProduct\)/]);
  assert.match(source('lib/seo.ts'), /https:\/\/schema\.org\/InStock/); matches(source('app/collections/[slug]/page.tsx'), [/generateMetadata/, /alternates: \{ canonical \}/, /notFound\(\)/, /"@type": "BreadcrumbList"/]); assert.match(source('app/collections/all/page.tsx'), /canonical: "\/collections\/all"/);
});
test('private and transactional storefront routes are noindex', () => { for (const file of ['app/account/layout.tsx', 'app/admin/layout.tsx', 'app/cart/page.tsx', 'app/checkout/page.tsx', 'app/order-confirmed/page.tsx', 'app/search/page.tsx', 'app/wishlist/page.tsx', 'app/review/[token]/page.tsx']) assert.match(source(file), /robots: \{ index: false, follow: false/); });
test('catalogue cards share media observers instead of creating one per card', () => { const code = source('components/product-card-media.tsx'); matches(code, [/useSyncExternalStore/, /mediaEnvironmentSubscribers/, /cardVisibilityObserver/, /observeCardVisibility\(node, setVisible\)/]); assert.doesNotMatch(code.slice(code.indexOf('function Gallery(')), /new IntersectionObserver/); });
test('collection LCP prioritizes only the leading product media', () => { assert.match(source('components/collection-browser.tsx'), /priorityMedia=\{index < 2\}/); assert.match(source('components/product-card.tsx'), /priority=\{priorityMedia\}/); matches(source('components/product-card-media.tsx'), [/priority=\{priority && index === 0\}/, /loading=\{priority \? "eager" : "lazy"\}/, /fetchPriority=\{priority \? "high" : undefined\}/]); });
test('homepage requests only a bounded featured catalogue payload', () => { const page = source('app/page.tsx'); assert.match(page, /getFeaturedProducts\(6\)/); assert.doesNotMatch(page, /getProducts\(\)/); assert.doesNotMatch(page, /getBestSellers\(/); assert.match(source('lib/api.ts'), /\/products\/featured/); matches(fs.readFileSync(path.resolve(__dirname, '../apps/api/src/products/products.service.ts'), 'utf8'), [/CARD_MEDIA_LIMIT = 3/, /toCardView/, /async featured\(limit = 4\)/]); });
test('homepage launch fallback is bounded, premium and navigable', async () => { const root = await harness({ products: catalogue }).homepage(); assert.equal(root.querySelectorAll('[data-qa-product]').length, 6); matches(root.text, [/THE HIDI EDIT/, /Pieces to live in now/, /Beautiful to look at/]); assert.equal(root.querySelector('.heroCta').getAttribute('href'), '/collections/all'); assert.equal(root.querySelector('.poster').getAttribute('src'), '/brand/hidi-hero-green-garden-fullbody.webp'); assert.match(root.querySelector('.poster').getAttribute('alt'), /full-length Indian wear styling/); assert.equal(root.querySelector('a[href="/about"]').getAttribute('href'), '/about'); assertReferencesResolve(root); });
test('homepage premium edit keeps real best sellers first when sales data exists', async () => { const bestSellers = [product(6), product(2), product(9)], root = await harness({ products: catalogue, bestSellers }).homepage(), cards = root.querySelectorAll('[data-qa-product]'); assert.equal(cards.length, 6); assert.deepEqual(cards.slice(0, bestSellers.length).map(card => card.getAttribute('data-qa-product')), bestSellers.map(item => item.slug)); assert.equal(cards[3].getAttribute('data-qa-product'), 'style-0'); assert.match(root.text, /Pieces to live in now/); assert.doesNotMatch(root.text, /A rotating edit led by what customers are choosing now/); });
test('Shop by Edit stays concise and shows the four approved categories', async () => { const root = await harness({ products: catalogue }).homepage(); matches(root.text, [/SHOP BY EDIT/, /Casual Wear\. Work Wear\. Occasional Wear\. Ananya’s Pick\./]); assert.doesNotMatch(root.text, /Three moods\. One HIDI point of view\./); assert.doesNotMatch(root.text, /Move from work to everyday plans/); });
test('homepage exposes the four core collection destinations without a marketplace strip', async () => { const root = await harness({ products: catalogue }).homepage(), hrefs = new Set(root.querySelectorAll('a').map(link => link.getAttribute('href'))); for (const href of ['/collections/casual-wear', '/collections/work-wear', '/collections/occasional-wear', '/collections/ananyas-pick']) assert.equal(hrefs.has(href), true); assert.equal(root.querySelector('[aria-label="Shop HIDI edits"]').querySelectorAll('a').length, 4); });
test('homepage showcases HIDI Privileges without turning into a discount banner', async () => { const root = await harness({ products: catalogue }).homepage(), section = root.querySelector('[aria-labelledby="hidi-privileges-title"]'); assert.ok(section); matches(section.text, [/The ₹1 HIDI Privilege/, /A Little Silver/, /HIDI Rewards/, /₹3,999\+/, /2 g silver launch keepsake/]); assert.equal(section.querySelectorAll('a').length, 3); assert.deepEqual(section.querySelectorAll('a').map(link => link.getAttribute('href')), ['/offers#rupee', '/offers#silver', '/account']); });
test('homepage follows the new editorial shopping flow without repeating promotional sections', () => { const page = source('app/page.tsx'), order = ['data-section="hero"', 'data-section="edits"', 'data-section="featured"', 'data-section="privileges"', 'data-section="craft"', '<EditorialLookbook', 'data-section="services"'], positions = order.map(marker => page.indexOf(marker)); assert(positions.every((position, i) => position >= 0 && (!i || position > positions[i - 1]))); assert.doesNotMatch(page, /principleGrid/); });
test('HIDI Privileges remains closed by default with keyboard-operable terms and responsive columns', async () => { const root = await harness({ products: catalogue }).homepage(), details = root.querySelector('details.privilegeDetails'); assert(details); assert.equal(details.hasAttribute('open'), false); assert.match(details.querySelector('summary').text, /Discover your privileges/); const file = 'app/home.module.css'; assert.equal(cssRule(file, '.privilegeGrid')['grid-template-columns'], 'repeat(3, minmax(0, 1fr))'); assert.equal(cssRule(file, '.privilegeGrid', '(max-width: 760px)')['grid-template-columns'], '1fr'); assert.equal(cssRule(file, '.privilegeSummary > span', '(prefers-reduced-motion: reduce)').transition, 'none'); });
test('homepage service strip communicates four practical shopping promises', async () => { const root = await harness({ products: catalogue }).homepage(), bar = root.querySelector('[aria-label="HIDI shopping services"]'); assert.ok(bar); assert.equal(bar.querySelectorAll('.serviceItem').length, 4); matches(bar.text, [/Complimentary shipping/, /Returns & exchanges/, /Secure checkout/, /Order & product help/]); });
test('homepage WhatsApp service falls back safely when no business number is configured', async () => { const root = await harness({ products: catalogue }).homepage(), link = root.querySelector('.serviceLink'); assert.equal(link.getAttribute('href'), '/contact'); assert.equal(link.hasAttribute('target'), false); });
test('homepage WhatsApp service creates a clean external handoff when configured', async () => { const root = await harness({ products: catalogue, whatsappNumber: '+91 99999 99999' }).homepage(), link = root.querySelector('.serviceLink'); assert.match(link.getAttribute('href'), /^https:\/\/wa\.me\/919999999999\?text=/); assert.equal(link.getAttribute('target'), '_blank'); assert.equal(link.getAttribute('rel'), 'noreferrer'); });
test('empty reviews remain calm without star or zero-count summaries', () => { const root = harness().reviews(emptyReviews); assert.match(root.text, /No reviews yet/); assert.equal(root.querySelector('.summary'), null); assert.equal(root.querySelector('[role="img"]'), null); assert.doesNotMatch(root.text, /0 reviews|☆☆☆☆☆|return window/i); assertReferencesResolve(root); });
test('review CTA is a native disclosure with truthful private-invitation guidance', () => { const root = harness().reviews(emptyReviews), details = root.querySelector('details.reviewGuidance'); assert.ok(details); assert.equal(details.hasAttribute('open'), false); assert.match(details.querySelector('summary').text, /How to write a review/); assert.match(details.text, /private link/); assert.equal(details.querySelector('a[href="/account"]').text.trim(), 'View my orders →'); assert.equal(root.querySelector('form'), null); });
test('populated reviews expose accessible ratings and retain the review disclosure', () => { const root = harness().reviews({ averageRating: 4.5, reviewCount: 2, reviews: [review, { ...review, id: 'r2', rating: 5 }] }); assert.equal(root.querySelectorAll('article').length, 2); assert.equal(root.querySelector('.summary [role=img]').getAttribute('aria-label'), '4.5 out of 5 stars'); assert.equal(root.querySelector('article [role=img]').getAttribute('aria-label'), '4 out of 5 stars'); assert.match(root.querySelector('.summary').text, /2 reviews/); assert.ok(root.querySelector('details summary')); assertReferencesResolve(root); });
test('unverified reviews never acquire a verified-purchase badge', () => { const root = harness().reviews({ averageRating: 4, reviewCount: 1, reviews: [{ ...review, verifiedPurchase: false }] }); assert.equal(root.querySelector('.verified'), null); assert.match(root.querySelector('.summary').text, /1 review\b/); assert.doesNotMatch(root.querySelector('.summary').text, /verified/); });
test('review copy renders as text, not customer-provided markup', () => { const root = harness().reviews({ averageRating: 4, reviewCount: 1, reviews: [{ ...review, body: '<script>alert("x")</script>', title: '<img src=x onerror="alert(1)">', reviewerName: '<b>Person</b>' }] }); assert.equal(root.querySelector('script'), null); assert.equal(root.querySelector('article img'), null); assert.equal(root.querySelector('article b'), null); assert.match(root.querySelector('article p').text, /<script>/); });
test('WhatsApp control is disabled and explained when no business number is configured', () => { const root = harness().contact(product(0)), trigger = root.querySelector('button[aria-haspopup="dialog"]'); assert.equal(trigger.hasAttribute('disabled'), true); assert.match(byId(root, trigger.getAttribute('aria-describedby')).text, /not available yet/); assert.equal(root.querySelector('dialog').hasAttribute('open'), false); assertReferencesResolve(root); });
test('configured WhatsApp dialog has labelled controls, icon and a truthful handoff note', () => { const root = harness({ whatsappNumber: '+919999999999' }).contact(product(0)), trigger = root.querySelector('button[aria-haspopup="dialog"]'), dialog = root.querySelector('dialog'); assert.equal(trigger.hasAttribute('disabled'), false); assert.equal(trigger.getAttribute('aria-controls'), dialog.getAttribute('id')); assert.equal(trigger.querySelector('svg').getAttribute('aria-hidden'), 'true'); assert.match(byId(root, dialog.getAttribute('aria-labelledby')).text, /Your selection/); assert.match(byId(root, dialog.getAttribute('aria-describedby')).text, /does not place an order or reserve stock/); assert.equal(dialog.querySelectorAll('select').length, 2); for (const select of dialog.querySelectorAll('select')) assert.ok(root.querySelectorAll('label').find(label => label.getAttribute('for') === select.getAttribute('id'))); assert.ok(dialog.querySelector('button[aria-label="Close WhatsApp selection"]')); assert.ok(dialog.querySelector('output[aria-live="polite"]')); assertReferencesResolve(root); });
test('initial WhatsApp selection never silently chooses size or bypasses stock verification', () => { const root = harness({ whatsappNumber: '+919999999999' }).contact(product(0)), dialog = root.querySelector('dialog'), size = dialog.querySelectorAll('select').find(select => select.getAttribute('id').endsWith('-size')); assert.equal(size.querySelector('option[selected]').getAttribute('value'), ''); assert.equal(size.querySelector('option[value="v0-l"]').hasAttribute('disabled'), true); assert.equal(dialog.querySelector('.continueButton').hasAttribute('disabled'), true); assert.equal(dialog.querySelectorAll('.quantityControl button[disabled]').length, 2); assert.equal(dialog.querySelector('.totalRow'), null); });
test('invalid configured WhatsApp numbers fail closed', () => { for (const whatsappNumber of ['', '123', 'https://wa.me/919999999999', 'not-a-number']) { const root = harness({ whatsappNumber }).contact(product(0)); assert.equal(root.querySelector('button[aria-haspopup="dialog"]').hasAttribute('disabled'), true); } });
test('review CTA and review submission have at least 48px minimum height', () => { assert.ok(parseFloat(cssRule('components/product-reviews.module.css', '.reviewButton')['min-height']) >= 48); assert.equal(cssRule('components/product-reviews.module.css', '.reviewButton', '(max-width: 620px)').width, '100%'); assert.ok(parseFloat(cssRule('app/review/[token]/review.module.css', '.submit')['min-height']) >= 48); });
test('homepage hero preserves the full-body garden composition on desktop', () => { const file = 'app/home.module.css', hero = cssRule(file, '.hero'); assert.equal(hero.width, '100%'); assert.equal(hero.height, 'auto'); assert.equal(hero['aspect-ratio'], '1672 / 941'); const image = cssRule('components/editorial-motion.module.css', '.poster'); assert.equal(image['object-fit'], 'cover'); assert.equal(image['object-position'], 'center'); const mobileHero = cssRule(file, '.hero', '(max-width: 760px)'); assert.equal(mobileHero['aspect-ratio'], 'auto'); assert.match(mobileHero.height, /clamp\(560px/); });
test('homepage section transitions stay compact without oversized blank gaps', () => { const file = 'app/home.module.css'; assert.match(cssRule(file, '.editSection')['padding-top'], /clamp\(36px/); matches(JSON.stringify(cssRule(file, '.featured')), [/clamp\(42px/, /clamp\(40px/]); assert.equal(cssRule(file, '.editSection', '(max-width: 760px)')['padding-top'], '36px'); const mobile = cssRule(file, '.featured', '(max-width: 760px)'); assert.equal(mobile['padding-top'], '42px'); assert.equal(mobile['padding-bottom'], '42px'); });
test('homepage premium interactions preserve desktop rhythm, mobile stacking and reduced motion', () => { const file = 'app/home.module.css'; assert.equal(cssRule(file, '.edits')['grid-template-columns'], '3fr 2fr'); assert.equal(cssRule(file, '.productGrid')['grid-template-columns'], 'repeat(3, minmax(0, 1fr))'); assert.equal(cssRule(file, '.serviceGrid')['grid-template-columns'], 'repeat(4, minmax(0, 1fr))'); assert.equal(cssRule(file, '.edits', '(max-width: 760px)')['grid-template-columns'], '1fr 1fr'); assert.equal(cssRule(file, '.editCard img', '(prefers-reduced-motion: reduce)').transition, 'none'); assert.equal(cssRule(file, '.serviceLink', '(prefers-reduced-motion: reduce)').transition, 'none'); assert.match(cssRule(file, '.craft')['padding-top'], /clamp\(42px/); assert.equal(cssRule(file, '.serviceItem')['min-height'], '88px'); });
test('craft and lookbook retain honest editorial attribution without unverified fabric or customer claims', async () => { const page = source('app/page.tsx'); matches(page, [/03-detail\.png/, /Fabric &amp; feel/, /Find your fit/]); assert.doesNotMatch(page, /Breathable Natural Weaves|Conscious Small-Batch Craft/); const root = await harness({ products: catalogue }).homepage(); assert.match(root.querySelector('[data-section="lookbook"]').text, /HIDI editorial photography/); assert.equal(root.querySelector('[aria-label="Customer styling photographs"]'), null); assert.equal(root.querySelector('[aria-label="Editorial lookbook"]').querySelectorAll('article').length, 6); });
test('storefront typography is build-safe and does not depend on Google font fetching', () => { assert.doesNotMatch(source('app/layout.tsx'), /next\/font\/google/); matches(source('app/globals.css'), [/--font-display:\s*Georgia/, /--font-product:[^;]*Futura[^;]*Century Gothic/]); });
test('HIDI theme keeps homepage and catalogue commerce on Mulberry, Gold and warm ivory', () => {
  assert.match(source('app/globals.css'), /HIDI AUTHORITATIVE BRAND TOKENS[\s\S]*--hidi-mulberry-clay:\s*#591d20;[\s\S]*--hidi-mulberry-gold:\s*#d5a24d;/); assert.equal(cssRule('app/home.module.css', '.craft').background, 'var(--home-paper)'); assert.match(cssRule('app/home.module.css', '.serviceStrip').background, /var\(--home-soft\)/);
  const selected = cssRule('components/product-card.module.css', '.fitRibbonSizeActive'); assert.equal(selected.background, 'var(--card-brand)'); assert.equal(selected.color, '#fff8ef'); assert.match(selected['box-shadow'], /rgba\(213,162,77/);
  const add = cssRule('components/product-card.module.css', '.addButton'); assert.equal(add.background, 'var(--card-brand)'); assert.equal(add.color, '#fff8ef');
  const buy = cssRule('components/product-card.module.css', '.buyButton'); assert.equal(buy.background, 'transparent'); assert.equal(buy.color, '#6f5f56'); const hover = cssRule('components/product-card.module.css', '.buyButton:hover:not(:disabled)'); assert.equal(hover.background, '#fffaf5'); assert.equal(hover.color, 'var(--card-brand)'); assert.equal(cssRule('components/collection-browser.module.css', '.filterCount').background, 'var(--hidi-mulberry-clay, #591d20)');
});
test('Option 1 footer keeps the HIDI ending dusty clay, gold and responsive', () => {
  const file = 'app/globals.css', footer = cssRule(file, '.footer'); assert.equal(footer.background, 'var(--footer-clay)'); assert.equal(footer.color, 'var(--footer-ink)'); assert.equal(footer['border-top'], '4px solid #d6b06b');
  matches(cssRule(file, '.footer-main').background, [/#96574f/, /var\(--footer-clay\)/, /#824943/]); assert.equal(cssRule(file, '.footer h3').color, 'var(--footer-gold-bright)'); assert.equal(cssRule(file, '.footer-grid a').color, '#fff3e8'); assert.equal(cssRule(file, '.footer-grid a:hover').color, 'var(--footer-gold-bright)'); assert.match(cssRule(file, '.footer-bottom-shell').background, /var\(--footer-clay-deep\)/);
  assert.equal(cssRule(file, '.footer .footer-grid', '(max-width: 620px)')['grid-template-columns'], '1fr 1fr'); assert.equal(cssRule(file, '.footer .footer-bottom', '(max-width: 620px)')['flex-direction'], 'column'); matches(source('components/site-footer.tsx'), [/footer-bottom-shell/, /Good clothes\. Brighter days\./, /\/collections\/casual-wear/, /\/collections\/work-wear/, /\/collections\/occasional-wear/, /\/collections\/ananyas-pick/]);
});
test('HIDI Privileges disclosure has usable interaction targets without loud hover panels', () => { const file = 'app/home.module.css'; assert.ok(parseFloat(cssRule(file, '.privilegeDetails summary')['min-height']) >= 44); assert.ok(parseFloat(cssRule(file, '.privilegeCard a')['min-height']) >= 44); assert.equal(cssRule(file, '.privilegeDetails[open] .privilegeSummary > span').transform, 'rotate(45deg)'); });
test('bag groups the same product and colour while preserving size controls', () => { matches(source('components/cart-client.tsx'), [/groupCartItems/, /item\.product\.id.*item\.variant\.color/s, /Qty \{group\.quantity\}/, /group\.items\.map/, /Size \{item\.variant\.size\}/, /formatPaise\(group\.lineTotalPaise\)/]); matches(fs.readFileSync(path.resolve(__dirname, '../apps/api/src/carts/carts.service.ts'), 'utf8'), [/cartId_variantId/, /nextQuantity = \(existing\?\.quantity \?\? 0\) \+ quantity/, /update: \{ quantity: nextQuantity/]); });
test('checkout PIN helper is advisory, sanitized and preserves editable delivery fields', () => {
  matches(source('components/checkout-client.tsx'), [/delivery-serviceability\?pin=/, /Delivery available/, /you can continue checkout/, /Live delivery check is temporarily unavailable/, /cityField\.value = next\.city/, /stateCode\.length > 2/, /cityField\.value === deliveryCheck\.city/]);
  const code = fs.readFileSync(path.resolve(__dirname, '../apps/api/src/checkout/checkout.controller.ts'), 'utf8'); matches(code, [/serviceable: result\.prepaid/, /city: result\.city \?\? null/, /30 \* 60_000/, /TOO_MANY_REQUESTS/]); assert.doesNotMatch(code, /raw: result\.raw/);
});
test('bag and checkout include the advertised complimentary-shipping threshold', () => { matches(source('components/cart-client.tsx'), [/complimentaryShipping = cart\.subtotalPaise >= 149900/, /shippingLabel/]); matches(source('components/checkout-client.tsx'), [/complimentaryShipping = cart\.subtotalPaise >= 149900/, /shippingLabel/]); });
test('checkout keeps guest purchase prominent and minimizes typing friction', () => { matches(source('components/checkout-client.tsx'), [/Checkout as guest — no account required/, /autoComplete="email"/, /autoComplete="tel"/, /autoComplete="shipping given-name"/, /autoComplete="shipping address-line1"/, /autoComplete="shipping postal-code"/, /autoComplete="shipping address-level2"/, /autoComplete="shipping address-level1"/, /Required for delivery and order updates/, /\+ Add apartment \/ landmark/, /showAddressDetail &&/, /Pay securely/, /className="checkout-edit-bag"/, /href="\/cart"/]); assert.equal(cssRule('app/globals.css', '.checkout-field').display, 'grid'); assert.equal(cssRule('app/globals.css', '.checkout-optional-toggle').background, 'transparent'); });
test('checkout keeps shipping promise, delivery assistance and recovery aligned', () => { matches(source('components/checkout-client.tsx'), [/cart\.subtotalPaise >= 149900/, /delivery-serviceability\?pin=/, /Delivery available/, /Live delivery check is temporarily unavailable/, /focusCheckoutProblem/, /Payment details are handled by Razorpay/, /selected stock is reserved while payment is prepared/]); assert.match(source('components/cart-client.tsx'), /cart\.subtotalPaise >= 149900/); assert.equal(cssRule('app/globals.css', '.checkout-payment-trust')['align-items'], 'flex-start'); });
test('HIDI Fit only presents verified garment measurements', () => { matches(source('components/add-to-cart.tsx'), [/Garment measurements/, /finished-garment measurements, not body measurements/, /HIDI will not estimate garment measurements/, /bustMm/, /garmentLengthMm/]); assert.equal(cssRule('components/add-to-cart.module.css', '.fitGuide').background, '#fffdfb'); });
test('WhatsApp ordering uses the recognisable WhatsApp mark', () => { matches(source('components/product-card.tsx'), [/WhatsAppIcon size=\{17\} className=\{styles\.whatsappIcon\}/, /> WhatsApp/]); assert.equal(cssRule('components/product-card.module.css', '.whatsappIcon').color, '#25d366'); assert.match(source('app/page.tsx'), /WhatsAppIcon size=\{18\} className=\{styles\.serviceWhatsappIcon\}/); });
test('HIDI Fit selected size toggles off when the same size is clicked again', () => { matches(source('components/product-card.tsx'), [/const deselecting = variantId === variant\.id;/, /setVariantId\(deselecting \? "" : variant\.id\);/, /rememberSelection\(deselecting \? undefined : variant\);/, /Unselect size/]); });
test('modal CSS bounds desktop size and allows content scrolling', () => { const modal = cssRule('components/product-contact-actions.module.css', '.modal'); assert.equal(modal.width, 'min(560px, calc(100% - 48px))'); assert.equal(modal['max-height'], 'calc(100dvh - 48px)'); assert.equal(modal['box-sizing'], 'border-box'); assert.equal(modal.overflow, 'auto'); assert.equal(modal['overscroll-behavior'], 'contain'); });
test('mobile modal CSS is a bounded bottom sheet with safe-area space and readable selects', () => { const file = 'components/product-contact-actions.module.css', mobile = '(max-width: 540px)', modal = cssRule(file, '.modal', mobile); assert.equal(modal.width, '100%'); assert.equal(modal.inset, 'auto 0 0'); assert.equal(modal['max-height'], '92dvh'); assert.match(modal.padding, /env\(safe-area-inset-bottom\)/); assert.equal(cssRule(file, '.modal select', mobile)['font-size'], 'var(--type-body)'); assert.equal(cssRule('app/typography.css', ':root')['--type-body'], '1rem'); });
test('modal actions retain usable target sizes, focus outlines and reduced-motion styles', () => { const file = 'components/product-contact-actions.module.css'; assert.ok(parseFloat(cssRule(file, '.actions .whatsapp')['min-height']) >= 48); assert.ok(parseFloat(cssRule(file, '.continueButton')['min-height']) >= 48); assert.ok(parseFloat(cssRule(file, '.modal select')['min-height']) >= 48); assert.ok(parseFloat(cssRule(file, '.quantityControl button').height) >= 44); assert.match(cssRule(file, '.modal button:focus-visible').outline, /3px solid/); assert.equal(cssRule(file, '.spinner', '(prefers-reduced-motion: reduce)').animation, 'none'); });
test('dialog source retains native-modal, cancellation and focus-return hooks', () => { matches(source('components/product-contact-actions.tsx'), [/element\.showModal\(\)/, /onCancel=\{\(\) => setOpen\(false\)\}/, /trigger\.current\?\.focus\(\)/, /document\.body\.style\.overflow = previousOverflow/, /request\.current\?\.abort\(\)/]); });
