'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowUpRight, Download, Package, RefreshCw, RotateCcw, ShoppingBag, Truck } from 'lucide-react';
import { count, downloadCsv, label, money, startForDays, today, useAdminData, when, type OrderRow, type Overview, type SeriesRow } from './admin-client';
import styles from './admin-workspace.module.css';

export function ErrorPanel({ message, retry }: { message: string; retry: () => void }) { return <section role="alert" className={styles.error}><strong>This view could not be loaded.</strong><p>{message}</p><button onClick={retry}>Try again</button></section>; }
export function LoadingPanel() { return <div className={styles.loading} role="status" aria-live="polite"><span className={styles.skeleton}/><span className={styles.skeleton}/><span className={styles.skeleton}/><p>Loading your HIDI data…</p></div>; }
export function StatusPill({ status }: { status: string }) { return <span className={styles.pill} data-status={status}>{label(status)}</span>; }
function Metric({ title, value, note, delta }: { title: string; value: string; note: string; delta?: number | null }) { return <article className={styles.metric}><p>{title}</p><strong className={styles.metricValue}>{value}</strong><div>{delta !== undefined && <span className={styles.delta} data-negative={delta !== null && delta < 0}>{delta === null ? 'No prior baseline' : `${delta > 0 ? '+' : ''}${delta}%`}</span>}<small>{note}</small></div></article>; }
export function OrderTable({ rows, delivery = false }: { rows: OrderRow[]; delivery?: boolean }) {
  return <div className={styles.tableWrap}><table className={styles.table}><caption className={styles.srOnly}>{delivery ? 'Delivery queue' : 'Orders'}</caption><thead><tr><th scope="col">Order</th><th scope="col">Customer</th><th scope="col">{delivery ? 'Carrier / AWB' : 'Items'}</th><th scope="col">Order total</th><th scope="col">{delivery ? 'Shipment update' : 'Payment'}</th><th scope="col">Status</th><th scope="col"><span className={styles.srOnly}>Action</span></th></tr></thead><tbody>{rows.map(order => <tr key={order.id}><td><Link className={styles.orderLink} href={`/admin/orders/${encodeURIComponent(order.orderNumber)}`}>{order.orderNumber}</Link><small>{when(order.createdAt)} IST</small></td><td><span>{order.customerPhone}</span><small>{order.customerEmail || 'No email provided'}</small></td><td>{delivery ? <><span>{order.shipments[0]?.provider || 'Not assigned'}</span><small>{order.shipments[0]?.awb || 'AWB pending'}</small></> : count(order.itemCount)}</td><td className={styles.numeric}>{money(order.totalPaise)}</td><td>{delivery ? <><span>{order.shipments[0] ? label(order.shipments[0].status) : 'Not manifested'}</span><small>{order.shipments[0] ? when(order.shipments[0].updatedAt) + ' IST' : 'Open order to manage'}</small></> : label(order.payments[0]?.status || 'Not recorded')}</td><td><StatusPill status={order.status}/></td><td><Link href={`/admin/orders/${encodeURIComponent(order.orderNumber)}`} className={styles.rowAction} aria-label={`Open order ${order.orderNumber}`}><ArrowUpRight size={18}/></Link></td></tr>)}</tbody></table></div>;
}
export function RevenueChart({ series }: { series: SeriesRow[] }) {
  const [metric, setMetric] = useState<'sales' | 'orders'>('sales');
  const current = series.map(row => metric === 'sales' ? row.salesPaise : row.orders);
  const previous = series.map(row => metric === 'sales' ? row.previousSalesPaise : row.previousOrders);
  const peak = Math.max(1, ...current, ...previous);
  const max = metric === 'orders' ? Math.ceil(peak / 4) * 4 : peak;
  const x = (i: number) => 66 + i / Math.max(series.length - 1, 1) * 676;
  const y = (v: number) => 208 - v / max * 174;
  const points = (values: number[]) => values.map((v, i) => `${x(i)},${y(v)}`).join(' ');
  const display = (n: number) => metric === 'sales' ? new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', notation: 'compact', maximumFractionDigits: 1 }).format(n / 100) : count(Math.round(n));
  return <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Sales at a glance</h2><p>Selected period against the previous equal-length period</p></div><div className={styles.segmented} aria-label="Chart metric"><button aria-pressed={metric === 'sales'} onClick={() => setMetric('sales')}>Value</button><button aria-pressed={metric === 'orders'} onClick={() => setMetric('orders')}>Orders</button></div></div><div className={styles.legend}><span><i/>Selected period</span><span><i/>Previous period</span></div>
    <svg viewBox="0 0 780 252" className={styles.chart} role="img" aria-labelledby="sales-chart-title sales-chart-description"><title id="sales-chart-title">{metric === 'sales' ? 'Daily booked order value in INR' : 'Daily confirmed order count'}</title><desc id="sales-chart-description">Current and previous period comparison. An accessible data table follows the chart. Unpaid and cancelled orders are excluded.</desc>{[0, 1, 2, 3, 4].map(tick => <g key={tick}><line x1="66" x2="742" y1={y(max * tick / 4)} y2={y(max * tick / 4)} className={styles.gridLine}/><text x="56" y={y(max * tick / 4) + 4} textAnchor="end">{display(max * tick / 4)}</text></g>)}{current.some(Boolean) && <polygon points={`66,208 ${points(current)} ${x(series.length - 1)},208`} className={styles.chartArea}/>}<polyline points={points(previous)} className={styles.previousLine}/><polyline points={points(current)} className={styles.currentLine}/>{series.map((row, i) => <g key={row.day}><circle tabIndex={0} aria-label={`${row.day}: ${metric === 'sales' ? money(row.salesPaise) : count(row.orders)}; previous ${metric === 'sales' ? money(row.previousSalesPaise) : count(row.previousOrders)}`} cx={x(i)} cy={y(current[i])} r="3" className={styles.chartPoint}><title>{row.day}: {metric === 'sales' ? money(row.salesPaise) : count(row.orders)}</title></circle>{(i === 0 || i === series.length - 1 || i % Math.max(1, Math.ceil(series.length / 5)) === 0) && <text x={x(i)} y="237" textAnchor="middle">{row.day.slice(8)} / {row.day.slice(5, 7)}</text>}</g>)}</svg>
    {!current.some(Boolean) && <p className={styles.chartNote}>No qualifying orders in this period. Zero values are shown, not sample data.</p>}
    <details className={styles.chartDetails}><summary>View chart data</summary><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Date (IST)</th><th>Booked value</th><th>Orders</th><th>Previous value</th><th>Previous orders</th></tr></thead><tbody>{series.map(row => <tr key={row.day}><td>{row.day}</td><td>{money(row.salesPaise)}</td><td>{row.orders}</td><td>{money(row.previousSalesPaise)}</td><td>{row.previousOrders}</td></tr>)}</tbody></table></div></details>
  </section>;
}
export function AdminOverview({ reports = false }: { reports?: boolean }) {
  const [range, setRange] = useState(() => ({ from: startForDays(30), to: today() }));
  const [draft, setDraft] = useState(range); const [dateError, setDateError] = useState('');
  const { data, error, loading, reload } = useAdminData<Overview>(`/api/admin/dashboard/overview?${new URLSearchParams(range)}`);
  function apply(next: { from: string; to: string }) {
    const days = (Date.parse(next.to) - Date.parse(next.from)) / 86400000 + 1;
    if (!next.from || !next.to || !Number.isFinite(days) || days < 1 || days > 90 || next.to > today()) { setDateError('Choose a valid past or current period of 1–90 days.'); return; }
    setDateError(''); setRange(next); setDraft(next);
  }
  function exportReport() { if (!data) return; downloadCsv(`hidi-daily-orders-${range.from}-${range.to}.csv`, [['Date (IST)', 'Booked order value (INR, not net revenue)', 'Qualifying orders', 'Previous period value (INR)', 'Previous period orders'], ...data.series.map(row => [row.day, (row.salesPaise / 100).toFixed(2), row.orders, (row.previousSalesPaise / 100).toFixed(2), row.previousOrders])]); }
  const queueCount = (status: string) => data?.pipeline.find(row => row.status === status)?.count ?? 0;
  return <main className={styles.page}>
    <div className={styles.pageHeading}><div><p className={styles.eyebrow}>YOUR BUSINESS, IN FOCUS</p><h1>{reports ? 'Sales & reports' : 'Overview'}</h1><p>{reports ? 'Understand your order trends. Export clearly defined daily figures.' : 'A clear view of sales, stock and every order that needs you.'}</p></div><div className={styles.actions}><button disabled={loading} onClick={reload}><RefreshCw size={16}/> Refresh</button><button disabled={!data || loading} className={styles.primary} onClick={exportReport}><Download size={16}/> Export daily report</button></div></div>
    <div className={styles.periodBar}><div className={styles.presets}>{[7, 30, 90].map(days => <button key={days} aria-pressed={range.from === startForDays(days) && range.to === today()} onClick={() => apply({ from: startForDays(days), to: today() })}>{days} days</button>)}</div><form className={styles.dateForm} onSubmit={event => { event.preventDefault(); apply(draft); }}><label>From<input type="date" value={draft.from} max={today()} onChange={event => setDraft({ ...draft, from: event.target.value })} required/></label><span aria-hidden="true">—</span><label>To<input type="date" value={draft.to} min={draft.from} max={today()} onChange={event => setDraft({ ...draft, to: event.target.value })} required/></label><button type="submit">Apply</button></form><small>IST · Today is incomplete</small></div>
    {dateError && <p role="alert" className={styles.error}>{dateError}</p>}{error && <ErrorPanel message={error} retry={reload}/>} {loading && <LoadingPanel/>}
    {data && !loading && <>
      <div className={styles.asOf}><span className={styles.smallDot}/> Database-backed · Updated {when(data.asOf)} IST <span>No automatic financial or delivery actions</span></div>
      <section className={styles.metrics} aria-label="Selected period metrics"><Metric title="Booked order value" value={money(data.metrics.salesPaise)} delta={data.metrics.salesChange} note="vs previous period · includes tax & shipping"/><Metric title="Confirmed orders" value={count(data.metrics.orders)} delta={data.metrics.ordersChange} note="Includes fulfilled and returned orders"/><Metric title="Average order value" value={money(data.metrics.aovPaise)} note="Booked value ÷ qualifying orders"/><Metric title="Processed cash refunds" value={money(data.metrics.processedCashRefundsPaise)} note="By processing date · excludes wallet credits"/></section>
      <div className={styles.chartRow}><RevenueChart series={data.series}/><section className={`${styles.panel} ${styles.attention}`}><p className={styles.eyebrow}>ACTION CENTRE · ALL DATES</p><h2>Needs your attention</h2><p>Focus on the next step, not the whole queue.</p>{[{ title: 'Ready to pack', value: queueCount('CONFIRMED'), icon: Package, href: '/admin/deliveries?status=CONFIRMED', note: 'Confirmed orders awaiting packing' }, { title: 'Ready to dispatch', value: queueCount('PACKED'), icon: Truck, href: '/admin/deliveries?status=PACKED', note: 'Packed orders awaiting shipment' }, { title: 'Returns & exchanges', value: data.metrics.pendingReturns, icon: RotateCcw, href: '/admin/returns', note: 'Active requests, including in progress' }, { title: 'Low-stock SKUs', value: data.metrics.lowStock, icon: ShoppingBag, href: '/admin/inventory', note: 'Available stock at or below reorder level' }].map(item => { const Icon = item.icon; return <Link key={item.title} href={item.href} className={styles.attentionItem}><span className={styles.attentionIcon}><Icon size={19}/></span><div><strong>{item.title}</strong><small>{item.note}</small></div><b>{count(item.value)}</b><ArrowUpRight size={16}/></Link>; })}</section></div>
      <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Fulfilment snapshot</h2><p>Current order status counts · all dates, not a conversion funnel</p></div><Link href="/admin/deliveries" className={styles.textLink}>Open delivery queue <ArrowUpRight size={16}/></Link></div><div className={styles.pipeline}>{['CONFIRMED', 'PACKED', 'SHIPPED', 'DELIVERED'].map((status, i) => <Link key={status} href={`/admin/deliveries?status=${status}`}><span className={styles.stageNumber}>0{i + 1}</span><div><small>{label(status)}</small><strong>{count(queueCount(status))}</strong></div><ArrowUpRight size={18}/></Link>)}</div></section>
      <div className={styles.bottomRow}><section className={styles.panel}><div className={styles.panelHeader}><div><h2>Top-selling designs</h2><p>Gross qualifying order units · before returns</p></div><Link href="/admin/products"><ArrowUpRight size={18}/><span className={styles.srOnly}>Open products</span></Link></div>{data.bestsellers.length ? data.bestsellers.map((product, index) => <Link className={styles.bestseller} key={product.productId} href={`/admin/products/${encodeURIComponent(product.productId)}`}><span>{String(index + 1).padStart(2, '0')}</span><div><strong>{product.name}</strong><div className={styles.productBar}><i style={{ width: `${Math.max(3, product.quantity / data.bestsellers[0].quantity * 100)}%` }}/></div></div><b>{count(product.quantity)} <small>units</small></b></Link>) : <p className={styles.empty}>Your bestsellers will appear after qualifying orders are recorded.</p>}</section><section className={`${styles.panel} ${styles.notes}`}><p className={styles.eyebrow}>KNOW YOUR NUMBERS</p><h2>Clarity before conclusions.</h2><p>{data.definitions.sales}</p><p>{data.definitions.refunds}</p><p>{data.definitions.comparison}</p><small>Profit, cash settlement, shipping costs, tax returns and marketing attribution are not inferred from order totals.</small></section></div>
      {!reports && <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Recent confirmed orders</h2><p>Latest eight across all dates · open an order to pack, ship, track or handle returns</p></div><Link className={styles.textLink} href="/admin/orders">All orders <ArrowUpRight size={16}/></Link></div>{data.recentOrders.length ? <OrderTable rows={data.recentOrders}/> : <p className={styles.empty}>No confirmed orders yet. Orders will appear here automatically.</p>}</section>}
    </>}
  </main>;
}
