import {readWorkbook} from './workbook-reader.mjs';
import {parseWorkbook,exactMatch,identityConflict,batchPayload,duplicateTargets,creationId,alreadyApplied,blankTemplate,categoryOption,savedIdentity,resultsCsv,sknMappingCsv,photoFileExample} from './product-batch.mjs';
const $=id=>document.getElementById(id),labels={name:'Product name',categoryId:'Category',shortDescription:'Short description',fabric:'Fabric',care:'Wash care',description:'Full product details'};
let items=[],catalog=[],options={categories:[],collections:[]},busy=false,ready=false,stop=false;
function say(message,type=''){ $('status').textContent=message;$('status').className='notice '+type; }
function lock(value){busy=value;for(const el of document.querySelectorAll('input,select,textarea,button'))el.disabled=value||(!ready&&el.id==='preview');$('stop').disabled=false;$('stop').hidden=!value||!items.length;}
async function api(path='',method='GET',body){const r=await fetch('/api/admin/products'+path,{method,credentials:'same-origin',cache:'no-store',...(body?{headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})});const data=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401||r.status===403)$('auth').hidden=false;const e=new Error(Array.isArray(data.message)?data.message.join('. '):data.message||'Product request failed ('+r.status+').');e.status=r.status;throw e;}return data;}
async function run(fn){if(busy)return;lock(true);try{await fn();}catch(e){say(e.message,'bad');}finally{lock(false);for(const row of items)if(row.status==='saved')row.ui?.querySelectorAll('input,select,textarea').forEach(e=>e.disabled=true);}}
async function loadCatalog(){const next=[];let page=1;for(;;){const result=await api('?status=ALL&page='+page);next.push(...(result.items||[]));if(next.length>=result.total||!result.items?.length)break;if(next.length>=5000)throw new Error('Catalogue exceeds 5,000 products. Use the existing product editor until catalogue pagination is extended.');page++;}catalog=next;}
const defaults=()=>Object.fromEntries(['color','sizes','price','mrp'].map(k=>[k,$('default-'+k).value.trim()]));
function state(row,message,type=''){row.resultMessage=message;row.ui.querySelector('.batch-state').textContent=message;row.ui.querySelector('.batch-state').className='batch-state notice '+type;}
function summary(){const selected=items.filter(r=>r.included&&r.status!=='saved').length,saved=items.filter(r=>r.status==='saved').length,failed=items.filter(r=>r.status==='failed').length;$('summary').textContent=items.length+' products · '+selected+' selected · '+saved+' saved'+(failed?' · '+failed+' failed':'');}
function currentAnanya(record){const id=options.collections?.find(c=>c.slug==='ananyas-pick')?.id;return Boolean(id&&record?.collections?.some(c=>c.collectionId===id));}
async function chooseTarget(row,id){const next=id?await api('/'+encodeURIComponent(id)):null;row.target=id;row.record=next;row.status='pending';row.attempted=null;if(row.identityError){row.error='';row.identityError=false;}if(row.ananyaPick===undefined)row.ui.querySelector('[data-ananya-choice]').checked=currentAnanya(next);state(row,row.record?'Manually selected: '+row.record.name+(row.record.skn?' · SKN '+row.record.skn:''):'Choose an existing product.');row.ui.querySelectorAll('.previous').forEach(el=>{const k=el.dataset.field;el.textContent='Current: '+(k==='categoryId'?row.record?.category?.name||'—':row.record?.[k]||'—');});}
function renderRow(row,index){
  const box=document.createElement('article');box.className='batch-product';row.ui=box;
  const head=document.createElement('div');head.className='batch-head';const selected=document.createElement('input');selected.type='checkbox';selected.checked=row.included;selected.setAttribute('aria-label','Include product '+(index+1));selected.onchange=()=>{row.included=selected.checked;summary();};const title=document.createElement('strong');title.textContent=(index+1)+'. '+(row.fields.name||row.id||row.sku||row.slug||'Unnamed product');head.append(selected,title);box.append(head);
  const source=document.createElement('p');source.className='meta';source.textContent=row.source+' · '+row.mode+(row.record?.skn?' · SKN '+row.record.skn:'');box.append(source);
  if(row.mode==='UPDATE'){const label=document.createElement('label');label.textContent='Existing HIDI product';const select=document.createElement('select');select.setAttribute('aria-label','Match product '+(index+1));select.append(new Option('Choose an existing product',''));if(row.record)select.append(new Option(row.record.name+' · '+row.record.status+(row.record.skn?' · SKN '+row.record.skn:''),row.record.id));let populated=false;select.onfocus=()=>{if(populated)return;for(const p of catalog)if(p.id!==row.record?.id)select.append(new Option(p.name+' · '+p.status+(p.skn?' · SKN '+p.skn:''),p.id));populated=true;};select.value=row.target;select.onchange=()=>run(()=>chooseTarget(row,select.value));label.append(select);box.append(label);}
  const message=document.createElement('p');message.className='batch-state notice';box.append(message);
  const details=document.createElement('details'),heading=document.createElement('summary');heading.textContent='Review / edit details';details.append(heading);
  if(row.warnings.length){const p=document.createElement('p');p.className='hint';p.textContent=row.warnings.join(' ');details.append(p);}
  const grid=document.createElement('div');grid.className='fields';
  for(const [key,label]of Object.entries(labels)){const group=document.createElement('div');if(key==='description')group.className='wide';const l=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=row.selected.has(key);check.setAttribute('aria-label','Product '+(index+1)+' save '+label);check.onchange=()=>{check.checked?row.selected.add(key):row.selected.delete(key);row.status='pending';};l.append(check,' '+label);group.append(l);
    const el=document.createElement(key==='categoryId'?'select':['description','shortDescription','care'].includes(key)?'textarea':'input');el.setAttribute('aria-label','Product '+(index+1)+' '+label);if(key==='categoryId'){el.append(new Option('No category / keep current',''));for(const c of options.categories)el.append(new Option(c.name,c.id));}if(el.tagName==='TEXTAREA')el.rows=key==='description'?8:3;el.value=row.fields[key]??row.record?.[key]??'';el.oninput=()=>{row.fields[key]=el.value;row.selected.add(key);check.checked=true;row.status='pending';};group.append(el);
    if(row.mode==='UPDATE'){const current=document.createElement('p');current.className='previous';current.dataset.field=key;current.textContent='Current: '+(key==='categoryId'?row.record?.category?.name||'—':row.record?.[key]||'—');group.append(current);}grid.append(group);
  }
  const pickGroup=document.createElement('div'),pickApplyLabel=document.createElement('label'),pickApply=document.createElement('input'),pickLabel=document.createElement('label'),pick=document.createElement('input');pickApply.type='checkbox';pickApply.checked=row.ananyaPick!==undefined;pickApply.setAttribute('aria-label','Product '+(index+1)+" save Ananya's Pick");pickApplyLabel.append(pickApply," Save Ananya's Pick choice");pick.type='checkbox';pick.dataset.ananyaChoice='true';pick.checked=row.ananyaPick??currentAnanya(row.record);pick.setAttribute('aria-label','Product '+(index+1)+" Ananya's Pick");pickLabel.append(pick," Include in Ananya's Pick");pickApply.onchange=()=>{row.ananyaPick=pickApply.checked?pick.checked:undefined;row.status='pending';};pick.onchange=()=>{pickApply.checked=true;row.ananyaPick=pick.checked;row.status='pending';};const pickHint=document.createElement('p');pickHint.className='hint';pickHint.textContent='Untick Save to keep the current choice. This collection can include products from any category.';pickGroup.append(pickApplyLabel,pickLabel,pickHint);grid.append(pickGroup);
  if(row.mode==='NEW')for(const [key,label]of Object.entries({color:'Colour',sizes:'Sizes (comma separated)',price:'Selling price (₹)',mrp:'MRP (₹)'})){const l=document.createElement('label');l.textContent=label;const el=document.createElement('input');el.setAttribute('aria-label','Product '+(index+1)+' '+label);el.value=key==='sizes'?row.sizes.join(', '):row[key];el.oninput=()=>{row[key]=key==='sizes'?el.value.toUpperCase().split(',').map(v=>v.trim()).filter(Boolean):el.value;row.status='pending';};l.append(el);grid.append(l);}
  details.append(grid);box.append(details);$('rows').append(box);state(row,row.error|| (row.mode==='NEW'?'New draft: review sizes and prices.':row.record?'Matched: '+row.record.name:'No unique match. Choose the existing HIDI product.'),row.error?'bad':'');
}
function checked(){const selected=items.filter(r=>r.included&&r.status!=='saved'),payloads=[],errors=new Map();selected.forEach((r,i)=>{try{payloads[i]=batchPayload(r,defaults(),options);}catch(e){errors.set(i,e.message);}});for(const [i,error]of duplicateTargets(selected,payloads))errors.set(i,error);selected.forEach((r,i)=>state(r,errors.get(i)||'Ready: '+(r.mode==='NEW'?'create draft':'update selected details'),errors.has(i)?'bad':'good'));summary();return {selected,payloads,errors};}
function download(name,text,type='text/csv'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('template').onclick=()=>download('hidi-product-details-blank.csv',blankTemplate);
$('preview').onclick=()=>run(async()=>{
  if(items.some(r=>r.status==='pending'||r.status==='failed')&&!window.confirm('Replace the current batch preview? Unsaved changes will be discarded.'))return;
  $('batch').hidden=true;say('Reading workbook. Nothing is being saved.');const parsed=parseWorkbook(await readWorkbook($('file').files[0]),$('mode').value);await loadCatalog();
  const next=parsed.entries;for(let i=0;i<next.length;i++){const row=next[i];if(row.category){const category=categoryOption(options,row.category);if(category){row.fields.categoryId=category.id;row.selected.add('categoryId');}else row.warnings.push('Category “'+row.category+'” needs your choice; the current category is retained.');}
    let match=exactMatch(row,catalog);
    if(row.mode==='UPDATE'&&row.sku&&!row.id&&!row.slug){const search=await api('?q='+encodeURIComponent(row.sku)+'&status=ALL');const matches=[];for(const p of search.items||[]){const full=await api('/'+encodeURIComponent(p.id));if(full.variants?.some(v=>v.sku===row.sku))matches.push(full);}if(matches.length===1)match=matches[0];}
    if(match){row.record=Array.isArray(match.variants)?match:await api('/'+encodeURIComponent(match.id));row.target=row.record.id;if(identityConflict(row,row.record)){row.error='Product identifiers disagree. Review and manually choose the intended product.';row.identityError=true;}}
    say('Preparing product '+(i+1)+' of '+next.length+'. Nothing has been saved.');
  }
  items=next;$('rows').replaceChildren();items.forEach(renderRow);$('batch').hidden=false;summary();checked();say('Batch preview ready. '+items.length+' products. '+(parsed.ignored.length?'Skipped sheets without products: '+parsed.ignored.join(', ')+'. ':'')+'Review matches and selected fields before saving.');
});
$('all').onclick=()=>{items.filter(r=>r.status!=='saved').forEach(r=>{r.included=true;r.ui.querySelector('.batch-head input').checked=true;});summary();};
$('none').onclick=()=>{items.forEach(r=>{r.included=false;r.ui.querySelector('.batch-head input').checked=false;});summary();};
$('validate').onclick=()=>{const c=checked();say(c.errors.size?c.errors.size+' selected products need attention. No products saved.':c.selected.length+' selected products are ready. No products saved.',c.errors.size?'bad':'good');};
$('stop').onclick=()=>{stop=true;$('stop').disabled=true;say('Pausing after the current product finishes.');};
$('saveTop').onclick=()=>{if(!busy)$('save').click();};
$('save').onclick=()=>run(async()=>{
  stop=false;const c=checked();if(!c.selected.length)throw new Error('Select at least one unsaved product.');if(c.errors.size)throw new Error('Fix or unselect '+c.errors.size+' products before saving. Nothing has been saved.');
  // Refresh before every save/retry to catch new products created since preview.
  await loadCatalog();for(let i=0;i<c.selected.length;i++){const row=c.selected[i],body=c.payloads[i];if(row.mode==='NEW'){body.requestId=await creationId(body);const expected='pm_'+body.requestId.replace(/-/g,'');if(catalog.some(p=>p.slug===body.slug&&p.id!==expected)){state(row,'A product already uses this URL. Use UPDATE or change product_slug.','bad');throw new Error('A new product URL already exists. Nothing has been saved.');}}}
  for(let i=0;i<c.selected.length&&!stop;i++){
    const row=c.selected[i],body=c.payloads[i];state(row,'Saving…');say('Saving '+(i+1)+' of '+c.selected.length+'.');
    try{
      if(row.mode==='UPDATE'&&row.attempted){const current=await api('/'+encodeURIComponent(row.record.id));if(alreadyApplied(current,body)){row.record=current;row.status='saved';row.included=false;row.ui.querySelector('.batch-head input').checked=false;state(row,'Saved (confirmed after retry).'+savedIdentity(current),'good');summary();continue;}}
      row.attempted=body;const saved=await api(row.mode==='NEW'?'':'/'+encodeURIComponent(row.record.id),row.mode==='NEW'?'POST':'PATCH',body);if(!saved.id)throw new Error('Save response is incomplete. Retry to confirm.');row.record=saved;row.status='saved';row.included=false;row.ui.querySelector('.batch-head input').checked=false;state(row,'Saved: '+saved.name+' · '+saved.status+savedIdentity(saved),'good');
    }catch(e){row.status='failed';state(row,'Failed: '+e.message,'bad');if([401,403].includes(e.status)){stop=true;}}
    summary();
  }
  const failed=items.filter(r=>r.status==='failed').length;say((stop?'Batch paused. ':'Batch finished. ')+items.filter(r=>r.status==='saved').length+' saved'+(failed?', '+failed+' failed. Review errors and save again to retry unsaved products.':'. Unsaved products remain in the preview.'),failed?'bad':'good');
});
$('report').onclick=()=>download('hidi-product-import-results.csv',resultsCsv(items));
$('skn-report').onclick=()=>{if(!items.some(r=>r.status==='saved'&&photoFileExample(r.record)))return say('Save products first to download their confirmed SKN photo mapping.','bad');download('hidi-product-skn-photo-mapping.csv',sknMappingCsv(items));};
window.addEventListener('beforeunload',e=>{if(busy||items.some(r=>r.included&&r.status!=='saved')){e.preventDefault();e.returnValue='';}});
void run(async()=>{options=await api('/options');ready=true;say('Ready. Upload your products to prepare a batch preview.');});
