import React, { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, Text, TextInput, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import ReanimatedSwipeable from "react-native-gesture-handler/ReanimatedSwipeable";
import { Minus, Plus, Tag, Trash2 } from "lucide-react-native";
import type { CartLine, Product } from "../domain";
import { money } from "../domain";
import { commerceApi } from "../api";
import { freeShippingThresholdPaise, mediaUrl } from "../config";
import { CachedImage, EmptyState, PrimaryButton, SectionHeading } from "../components/Primitives";
import { ProductCard } from "../components/ProductCard";
import { useCommerce } from "../store";
import { colors } from "../theme";

function BagLine({ line, busy, onQuantity, onRemove }: { line: CartLine; busy: boolean; onQuantity: (quantity: number) => void; onRemove: () => void }) {
  const right = () => <Pressable accessibilityRole="button" accessibilityLabel={`Remove ${line.product.name}`} onPress={onRemove} className="ml-2 w-24 items-center justify-center rounded-xl bg-sale"><Trash2 size={23} color="white" /><Text className="mt-1 text-xs font-extrabold text-white">REMOVE</Text></Pressable>;
  return <ReanimatedSwipeable renderRightActions={right} friction={2} rightThreshold={45}><View className="mb-3 flex-row rounded-card border border-line bg-white p-3"><View className="h-32 w-24 overflow-hidden rounded-lg bg-soft"><CachedImage source={{ uri: mediaUrl(line.product.image) }} className="h-full w-full" resizeMode="cover" fallbackLabel={line.product.name} /></View><View className="ml-3 flex-1"><Text numberOfLines={1} className="font-black text-ink">HIDI</Text><Text numberOfLines={2} className="mt-0.5 text-sm text-muted">{line.product.name}</Text><Text className="mt-2 text-xs font-semibold text-ink">{line.variant.color} · Size {line.variant.size}</Text><Text className="mt-2 font-black text-ink">{money(line.unitPricePaise)}</Text><View className="mt-3 flex-row items-center self-start rounded-lg border border-line"><Pressable disabled={busy || line.quantity <= 1} onPress={() => onQuantity(line.quantity - 1)} className="h-10 w-10 items-center justify-center"><Minus size={16} color={line.quantity <= 1 ? "#bbb" : colors.ink} /></Pressable><Text className="min-w-8 text-center font-black text-ink">{line.quantity}</Text><Pressable disabled={busy || line.quantity >= line.variant.available} onPress={() => onQuantity(line.quantity + 1)} className="h-10 w-10 items-center justify-center"><Plus size={16} color={line.quantity >= line.variant.available ? "#bbb" : colors.ink} /></Pressable></View></View></View></ReanimatedSwipeable>;
}

export default function BagScreen() {
  const navigation = useNavigation<any>(); const store = useCommerce(); const [promo, setPromo] = useState(""); const [promoMessage, setPromoMessage] = useState(""); const [crossSell, setCrossSell] = useState<Product[]>([]);
  useEffect(() => { const slug = store.cart?.items[0]?.product.slug; if (slug) void commerceApi.relatedForBag(slug).then(value => setCrossSell(value.slice(0, 6))).catch(() => undefined); else setCrossSell([]); }, [store.cart?.items[0]?.product.slug]);
  async function applyPromo() { if (!promo.trim()) return; setPromoMessage("Checking code…"); try { const sessionId = store.cart?.sessionId ?? ""; const result = await commerceApi.validatePromo(promo.trim().toUpperCase(), sessionId); setPromoMessage(result.valid ? result.message ?? "Code applied. Totals will be reconfirmed at checkout." : result.message ?? "This code is not valid for the current bag."); } catch { setPromoMessage("Promotion validation is not available from the current store service. No discount was applied."); } }
  const progress = useMemo(() => freeShippingThresholdPaise > 0 ? Math.min(1, (store.cart?.subtotalPaise ?? 0) / freeShippingThresholdPaise) : 0, [store.cart?.subtotalPaise]);
  if (!store.cart && !store.cartError) return <View className="flex-1 items-center justify-center bg-white"><ActivityIndicator color={colors.accent} /></View>;
  if (!store.cart?.items.length) return <View className="flex-1 bg-white"><View className="px-4 pb-3 pt-5"><Text className="text-3xl font-black text-ink">Bag</Text></View><EmptyState title="Your bag is waiting." body="Add an exact size from any product page and it will appear here." action="Start shopping" onAction={() => navigation.navigate("Categories")} /></View>;
  return <View className="flex-1 bg-white"><View className="min-h-16 flex-row items-center justify-between px-4"><View><Text className="text-3xl font-black text-ink">Bag</Text><Text className="text-sm text-muted">{store.cart.itemCount} {store.cart.itemCount === 1 ? "item" : "items"}</Text></View>{store.cartBusy ? <ActivityIndicator color={colors.accent} /> : null}</View>
    <FlatList data={store.cart.items} keyExtractor={item => item.id} contentContainerStyle={{ paddingHorizontal: 16, paddingBottom: 260 }} renderItem={({ item }) => <BagLine line={item} busy={store.cartBusy} onQuantity={quantity => void store.updateQuantity(item.id, quantity)} onRemove={() => void store.removeLine(item.id)} />} ListFooterComponent={<View>
      {freeShippingThresholdPaise > 0 ? <View className="my-4 rounded-card bg-soft p-4"><Text className="font-extrabold text-ink">{store.cart.subtotalPaise >= freeShippingThresholdPaise ? "Free shipping unlocked" : `${money(freeShippingThresholdPaise - store.cart.subtotalPaise)} away from free shipping`}</Text><View className="mt-3 h-2 overflow-hidden rounded-full bg-gray-200"><View style={{ width: `${progress * 100}%` }} className="h-full rounded-full bg-accent" /></View></View> : null}
      <View className="mt-2 rounded-card border border-line p-4"><View className="flex-row items-center gap-2"><Tag size={19} color={colors.accent} /><Text className="text-base font-black text-ink">Have a coupon?</Text></View><View className="mt-3 flex-row gap-2"><TextInput value={promo} onChangeText={setPromo} autoCapitalize="characters" placeholder="Enter code" placeholderTextColor={colors.muted} className="min-h-12 flex-1 rounded-xl border border-line px-4 text-ink" /><Pressable onPress={() => void applyPromo()} className="min-h-12 justify-center rounded-xl border border-accent px-5"><Text className="font-extrabold text-accent">APPLY</Text></Pressable></View>{promoMessage ? <Text className="mt-3 text-sm leading-5 text-muted">{promoMessage}</Text> : null}</View>
      <View className="mt-5 rounded-card border border-line p-4"><Text className="text-lg font-black text-ink">Price details</Text><View className="mt-4 flex-row justify-between"><Text className="text-muted">Bag subtotal</Text><Text className="font-bold text-ink">{money(store.cart.subtotalPaise)}</Text></View><View className="mt-3 flex-row justify-between"><Text className="text-muted">Shipping</Text><Text className="font-bold text-ink">Calculated at checkout</Text></View><View className="mt-3 flex-row justify-between"><Text className="text-muted">Taxes</Text><Text className="font-bold text-ink">Confirmed by checkout</Text></View><View className="mt-4 border-t border-line pt-4"><View className="flex-row justify-between"><Text className="text-base font-black text-ink">Current subtotal</Text><Text className="text-base font-black text-ink">{money(store.cart.subtotalPaise)}</Text></View></View></View>
      {crossSell.length ? <View className="-mx-4 mt-6"><SectionHeading title="Complete the look" /><FlatList horizontal showsHorizontalScrollIndicator={false} data={crossSell} keyExtractor={item => item.id} contentContainerStyle={{ paddingHorizontal: 10 }} renderItem={({ item }) => <View className="w-44"><ProductCard product={item} widthClass="w-full" saved={store.wishlist.includes(item.slug)} onToggleSaved={() => void store.toggleWishlist(item.slug)} onOpen={() => navigation.navigate("Product", { slug: item.slug })} /></View>} /></View> : null}
    </View>} />
    <View className="absolute bottom-0 left-0 right-0 border-t border-line bg-white px-4 pb-4 pt-3"><View className="mb-3 flex-row items-center justify-between"><Text className="text-sm text-muted">Subtotal</Text><Text className="text-xl font-black text-ink">{money(store.cart.subtotalPaise)}</Text></View><PrimaryButton label="PROCEED TO ADDRESS" onPress={() => navigation.navigate("CheckoutAddress")} />{store.cartError ? <Text className="mt-2 text-center text-xs text-sale">{store.cartError}</Text> : null}</View>
  </View>;
}
