import React, { useState } from "react";
import { Pressable, ScrollView, Text, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { Check, MapPin, Plus, ShieldCheck } from "lucide-react-native";
import type { RootStackParamList } from "../navigation/types";
import type { Address } from "../domain";
import { money } from "../domain";
import { commerceApi } from "../api";
import { BrandHeader } from "../components/Chrome";
import { Field, PrimaryButton, SecondaryButton } from "../components/Primitives";
import { useCommerce } from "../store";
import { storage } from "../storage";
import { colors } from "../theme";

type AddressProps = NativeStackScreenProps<RootStackParamList, "CheckoutAddress">;
export function CheckoutAddressScreen({ navigation }: AddressProps) {
  const store = useCommerce(); const [adding, setAdding] = useState(!store.addresses.length); const [form, setForm] = useState<Omit<Address, "id">>({ name: "", phone: "", line1: "", line2: "", city: "", state: "", pin: "", isDefault: true }); const [error, setError] = useState("");
  async function save() { if (!form.name.trim() || !/^[6-9]\d{9}$/.test(form.phone.replace(/\D/g, "")) || !form.line1.trim() || !form.city.trim() || !form.state.trim() || !/^\d{6}$/.test(form.pin)) { setError("Complete the required address fields with a valid mobile number and PIN code."); return; } const address = { ...form, phone: form.phone.replace(/\D/g, ""), id: storage.newAddressId() }; await store.saveAddress(address); setAdding(false); navigation.navigate("CheckoutSummary", { addressId: address.id }); }
  return <View className="flex-1 bg-white"><BrandHeader navigation={navigation} title="ADDRESS" /><ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 40 }}><View className="mb-6 flex-row items-center gap-3"><View className="h-9 w-9 items-center justify-center rounded-full bg-accent"><Text className="font-black text-white">1</Text></View><Text className="text-xl font-black text-ink">Choose delivery address</Text></View>{store.addresses.map(address => <Pressable key={address.id} onPress={() => navigation.navigate("CheckoutSummary", { addressId: address.id })} className="mb-3 rounded-card border border-line p-4"><View className="flex-row gap-3"><MapPin size={21} color={colors.accent} /><View className="flex-1"><Text className="font-black text-ink">{address.name}</Text><Text className="mt-1 text-sm leading-5 text-muted">{address.line1}{address.line2 ? `, ${address.line2}` : ""}, {address.city}, {address.state} · {address.pin}</Text><Text className="mt-2 text-sm font-semibold text-ink">+91 {address.phone}</Text></View><Check size={20} color={colors.success} /></View></Pressable>)}
    {!adding ? <Pressable onPress={() => setAdding(true)} className="min-h-14 flex-row items-center justify-center gap-2 rounded-xl border border-accent"><Plus size={20} color={colors.accent} /><Text className="font-extrabold text-accent">ADD NEW ADDRESS</Text></Pressable> : <View className="gap-4 rounded-card border border-line p-4"><Text className="text-lg font-black text-ink">New address</Text><Field label="Full name" value={form.name} onChangeText={name => setForm(f => ({ ...f, name }))} /><Field label="Mobile number" value={form.phone} keyboardType="phone-pad" onChangeText={phone => setForm(f => ({ ...f, phone }))} /><Field label="Address line" value={form.line1} onChangeText={line1 => setForm(f => ({ ...f, line1 }))} /><Field label="Apartment / landmark (optional)" value={form.line2} onChangeText={line2 => setForm(f => ({ ...f, line2 }))} /><View className="flex-row gap-3"><View className="flex-1"><Field label="City" value={form.city} onChangeText={city => setForm(f => ({ ...f, city }))} /></View><View className="flex-1"><Field label="State" value={form.state} onChangeText={state => setForm(f => ({ ...f, state }))} /></View></View><Field label="PIN code" value={form.pin} keyboardType="number-pad" onChangeText={pin => setForm(f => ({ ...f, pin: pin.replace(/\D/g, "").slice(0, 6) }))} error={error} /><PrimaryButton label="SAVE & DELIVER HERE" onPress={() => void save()} /></View>}</ScrollView></View>;
}

type SummaryProps = NativeStackScreenProps<RootStackParamList, "CheckoutSummary">;
export function CheckoutSummaryScreen({ navigation, route }: SummaryProps) {
  const store = useCommerce(); const address = store.addresses.find(item => item.id === route.params.addressId); const [service, setService] = useState<{ serviceable: boolean; copy: string } | null>(null); const [busy, setBusy] = useState(false);
  async function check() { if (!address) return; setBusy(true); try { const value = await commerceApi.serviceability(address.pin); setService({ serviceable: value.serviceable, copy: value.serviceable ? "Delivery is available. Final date, shipping and tax are confirmed by checkout." : "Delivery is not currently available to this PIN code." }); } catch (error) { setService({ serviceable: false, copy: error instanceof Error ? error.message : "Delivery could not be checked." }); } finally { setBusy(false); } }
  if (!address || !store.cart) return <View className="flex-1 items-center justify-center bg-white"><Text className="text-muted">Address or bag is unavailable.</Text></View>;
  return <View className="flex-1 bg-white"><BrandHeader navigation={navigation} title="SUMMARY" /><ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 150 }}><View className="mb-6 flex-row items-center gap-3"><View className="h-9 w-9 items-center justify-center rounded-full bg-accent"><Text className="font-black text-white">2</Text></View><Text className="text-xl font-black text-ink">Review your order</Text></View><View className="rounded-card border border-line p-4"><Text className="font-black text-ink">Deliver to {address.name}</Text><Text className="mt-2 text-sm leading-5 text-muted">{address.line1}, {address.city}, {address.state} · {address.pin}</Text><Pressable onPress={() => navigation.goBack()} className="mt-3 self-start"><Text className="font-extrabold text-accent">CHANGE</Text></Pressable></View><View className="mt-5 rounded-card border border-line p-4"><Text className="text-lg font-black text-ink">{store.cart.itemCount} items</Text>{store.cart.items.map(line => <View key={line.id} className="mt-4 flex-row justify-between gap-3 border-t border-line pt-4"><View className="flex-1"><Text className="font-bold text-ink">{line.product.name}</Text><Text className="mt-1 text-xs text-muted">{line.variant.color} · {line.variant.size} · Qty {line.quantity}</Text></View><Text className="font-black text-ink">{money(line.lineTotalPaise)}</Text></View>)}</View><View className="mt-5 rounded-card border border-line p-4"><View className="flex-row justify-between"><Text className="text-muted">Bag subtotal</Text><Text className="font-bold text-ink">{money(store.cart.subtotalPaise)}</Text></View><View className="mt-3 flex-row justify-between"><Text className="text-muted">Shipping & taxes</Text><Text className="font-bold text-ink">Confirmed next</Text></View></View><View className="mt-5"><PrimaryButton label={service?.serviceable ? "CONTINUE TO PAYMENT" : "CHECK DELIVERY"} loading={busy} onPress={() => service?.serviceable ? navigation.navigate("CheckoutPayment", { addressId: address.id }) : void check()} /></View>{service ? <Text className={`mt-3 text-sm leading-5 ${service.serviceable ? "text-success" : "text-sale"}`}>{service.copy}</Text> : null}</ScrollView></View>;
}

type PaymentProps = NativeStackScreenProps<RootStackParamList, "CheckoutPayment">;
export function CheckoutPaymentScreen({ navigation }: PaymentProps) {
  const store = useCommerce();
  const amount = store.cart?.subtotalPaise ?? 0;
  return <View className="flex-1 bg-white"><BrandHeader navigation={navigation} title="PAYMENT" /><View className="flex-1 px-5 pt-10"><View className="h-16 w-16 items-center justify-center rounded-full bg-pink-50"><ShieldCheck size={30} color={colors.accent} /></View><Text className="mt-6 text-3xl font-black text-ink">Secure payment is not configured.</Text><Text className="mt-3 text-base leading-6 text-muted">Address selection, delivery validation and order summary are ready. Payment will be enabled only after an approved mobile payment provider, production keys, merchant identifiers and redirect or deep-link handling are configured.</Text><View className="mt-6 rounded-card bg-soft p-4"><View className="flex-row justify-between"><Text className="text-muted">Current bag subtotal</Text><Text className="text-lg font-black text-ink">{money(amount)}</Text></View><Text className="mt-2 text-xs leading-5 text-muted">No payment attempt or order has been created from this screen.</Text></View><View className="mt-8"><SecondaryButton label="Back to order summary" onPress={() => navigation.goBack()} /></View></View></View>;
}
