import React, { useEffect, useMemo, useRef, useState } from "react";
import { FlatList, Pressable, ScrollView, Text, TextInput, useWindowDimensions, Vibration, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { BottomSheetModal, BottomSheetScrollView } from "@gorhom/bottom-sheet";
import Animated, { useAnimatedStyle, useSharedValue, withSpring } from "react-native-reanimated";
import { ChevronDown, ChevronUp, Heart, Ruler, ShieldCheck, Truck } from "lucide-react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../navigation/types";
import { commerceApi } from "../api";
import type { Product, Variant } from "../domain";
import { discountPercent, money, productMrp } from "../domain";
import { mediaUrl } from "../config";
import { BrandHeader } from "../components/Chrome";
import { CachedImage, PrimaryButton, Skeleton } from "../components/Primitives";
import { ProductCard } from "../components/ProductCard";
import { useCommerce } from "../store";
import { storage } from "../storage";
import { colors, shadows } from "../theme";

type Props = NativeStackScreenProps<RootStackParamList, "Product">;
function Accordion({ title, children }: React.PropsWithChildren<{ title: string }>) { const [open, setOpen] = useState(false); return <View className="border-b border-line"><Pressable accessibilityRole="button" accessibilityState={{ expanded: open }} onPress={() => setOpen(x => !x)} className="min-h-14 flex-row items-center justify-between py-3"><Text className="text-base font-extrabold text-ink">{title}</Text>{open ? <ChevronUp size={19} color={colors.ink} /> : <ChevronDown size={19} color={colors.ink} />}</Pressable>{open ? <View className="pb-5"><Text className="text-sm leading-6 text-muted">{children}</Text></View> : null}</View>; }
function VariantChoice({ value, selected, disabled, onPress }: { value: string; selected: boolean; disabled?: boolean; onPress: () => void }) { return <Pressable accessibilityRole="radio" accessibilityState={{ selected, disabled }} disabled={disabled} onPress={onPress} className={`min-h-12 min-w-12 items-center justify-center rounded-xl border px-4 ${selected ? "border-accent bg-pink-50" : disabled ? "border-line bg-gray-100" : "border-line bg-white"}`}><Text className={`font-extrabold ${selected ? "text-accent" : disabled ? "text-gray-400 line-through" : "text-ink"}`}>{value}</Text></Pressable>; }

export default function ProductScreen({ navigation, route }: Props) {
  const store = useCommerce(); const { width } = useWindowDimensions(); const [detail, setDetail] = useState<Product | undefined>(() => store.product(route.params.slug)); const [loading, setLoading] = useState(!detail); const [related, setRelated] = useState<Product[]>([]);
  const [color, setColor] = useState(""); const [variant, setVariant] = useState<Variant | null>(null); const [deliveryPin, setDeliveryPin] = useState(""); const [deliveryCopy, setDeliveryCopy] = useState(""); const [added, setAdded] = useState(false);
  const sizeSheet = useRef<BottomSheetModal>(null); const fitSheet = useRef<BottomSheetModal>(null); const heartScale = useSharedValue(1); const heartStyle = useAnimatedStyle(() => ({ transform: [{ scale: heartScale.value }] }));
  useEffect(() => { let alive = true; void storage.remember(route.params.slug); if (!detail) void commerceApi.product(route.params.slug).then(value => { if (alive) setDetail(value); }).finally(() => { if (alive) setLoading(false); }); void commerceApi.related(route.params.slug).then(value => { if (alive) setRelated(value.slice(0, 8)); }).catch(() => undefined); return () => { alive = false; }; }, [route.params.slug]);
  useEffect(() => { if (!detail) return; const first = detail.variants.find(v => v.available > 0)?.color ?? detail.variants[0]?.color ?? ""; setColor(first); setVariant(null); }, [detail?.id]);
  const colorsAvailable = useMemo(() => Array.from(new Set((detail?.variants ?? []).map(v => v.color).filter(Boolean))), [detail]);
  const colorVariants = useMemo(() => (detail?.variants ?? []).filter(v => !color || v.color === color), [detail, color]);
  const saved = store.wishlist.includes(route.params.slug); const discount = detail ? discountPercent(detail) : 0; const mrp = detail ? productMrp(detail) : 0;
  function toggleSaved() { Vibration.vibrate(12); heartScale.value = 0.7; heartScale.value = withSpring(1, { damping: 7, stiffness: 230 }); void store.toggleWishlist(route.params.slug); }
  async function add() { if (!variant) { sizeSheet.current?.present(); return; } await store.addToBag(variant.id, 1); setAdded(true); Vibration.vibrate(20); }
  async function checkDelivery() { if (!/^\d{6}$/.test(deliveryPin)) { setDeliveryCopy("Enter a valid six-digit PIN code."); return; } setDeliveryCopy("Checking…"); try { const result = await commerceApi.serviceability(deliveryPin); setDeliveryCopy(result.serviceable ? `Delivery is available${result.city ? ` in ${result.city}` : ""}. Final date and charges are confirmed at checkout.` : "Delivery is not currently available to this PIN code."); } catch (error) { setDeliveryCopy(error instanceof Error ? error.message : "Delivery could not be checked."); } }
  if (loading || !detail) return <View className="flex-1 bg-white px-4 pt-12"><Skeleton className="aspect-[4/5] w-full" /><Skeleton className="mt-5 h-8 w-3/4" /><Skeleton className="mt-3 h-5 w-1/2" /></View>;
  const images = [...detail.images].sort((a, b) => (a.position ?? 0) - (b.position ?? 0));
  return <View className="flex-1 bg-white"><BrandHeader navigation={navigation} />
    <ScrollView className="flex-1" contentContainerStyle={{ paddingBottom: 126 }} showsVerticalScrollIndicator={false}>
      <FlatList horizontal pagingEnabled showsHorizontalScrollIndicator={false} data={images.length ? images : [{ id: "fallback", url: "", alt: detail.name }]} keyExtractor={item => item.id} renderItem={({ item, index }) => <View style={{ width }} className="aspect-[4/5] bg-soft"><CachedImage source={{ uri: mediaUrl(item.url) }} className="h-full w-full" resizeMode="cover" fallbackLabel={detail.name} /><View className="absolute bottom-4 right-4 rounded-full bg-black/70 px-3 py-1"><Text className="text-xs font-bold text-white">{index + 1}/{Math.max(images.length, 1)}</Text></View></View>} />
      <View className="px-4 pt-5"><View className="flex-row items-start justify-between gap-4"><View className="flex-1"><Text className="text-base font-black tracking-wide text-ink">{detail.brand || "HIDI"}</Text><Text className="mt-1 text-lg text-muted">{detail.name}</Text></View><Animated.View style={heartStyle}><Pressable accessibilityRole="button" accessibilityLabel={saved ? "Remove from wishlist" : "Add to wishlist"} onPress={toggleSaved} className="h-12 w-12 items-center justify-center rounded-full border border-line"><Heart size={23} color={colors.accent} fill={saved ? colors.accent : "transparent"} /></Pressable></Animated.View></View>
        <View className="mt-4 flex-row flex-wrap items-center gap-x-3 gap-y-1"><Text className="text-xl font-black text-ink">{money(detail.minPricePaise)}</Text>{mrp > detail.minPricePaise ? <Text className="text-sm text-gray-400 line-through">{money(mrp)}</Text> : null}{discount ? <Text className="text-sm font-extrabold text-success">({discount}% OFF)</Text> : null}</View><Text className="mt-1 text-xs text-muted">Inclusive of applicable taxes where provided by the canonical checkout.</Text>
        {colorsAvailable.length > 1 ? <><Text className="mb-3 mt-7 text-base font-black text-ink">COLOUR · {color}</Text><View className="flex-row flex-wrap gap-3">{colorsAvailable.map(value => <VariantChoice key={value} value={value} selected={color === value} onPress={() => { setColor(value); setVariant(null); }} />)}</View></> : null}
        <View className="mt-7 flex-row items-center justify-between"><Text className="text-base font-black text-ink">SELECT SIZE</Text><Pressable onPress={() => fitSheet.current?.present()} className="min-h-11 flex-row items-center gap-2"><Ruler size={18} color={colors.accent} /><Text className="font-bold text-accent">FIND MY SIZE</Text></Pressable></View><View className="mt-3 flex-row flex-wrap gap-3">{colorVariants.map(value => <VariantChoice key={value.id} value={value.size} selected={variant?.id === value.id} disabled={value.available <= 0} onPress={() => setVariant(value)} />)}</View>
        {variant?.available && variant.available <= 3 ? <Text className="mt-3 text-sm font-bold text-sale">Only {variant.available} left in this size</Text> : null}
        <View className="mt-8 rounded-card border border-line p-4"><View className="flex-row items-center gap-3"><Truck size={21} color={colors.ink} /><Text className="text-base font-extrabold text-ink">Check delivery</Text></View><View className="mt-3 flex-row gap-2"><TextInput value={deliveryPin} onChangeText={value => setDeliveryPin(value.replace(/\D/g, "").slice(0, 6))} keyboardType="number-pad" placeholder="Enter PIN code" placeholderTextColor={colors.muted} className="min-h-12 flex-1 rounded-xl border border-line px-4 text-ink" /><Pressable onPress={() => void checkDelivery()} className="min-h-12 justify-center rounded-xl bg-ink px-4"><Text className="font-extrabold text-white">CHECK</Text></Pressable></View>{deliveryCopy ? <Text className="mt-3 text-sm leading-5 text-muted">{deliveryCopy}</Text> : null}</View>
        <View className="mt-5"><Accordion title="Product details">{detail.description || detail.shortDescription || "Product details are being updated."}</Accordion><Accordion title="Fabric & care">{[detail.fabric ? `Fabric: ${detail.fabric}.` : "", detail.care || "Follow the care label supplied with the garment."].filter(Boolean).join(" ")}</Accordion><Accordion title="Delivery & returns">Final delivery, return and exchange eligibility are confirmed against the current HIDI policy and order state at checkout.</Accordion></View>
        <View className="mt-6 flex-row items-center gap-3 rounded-xl bg-soft p-4"><ShieldCheck size={22} color={colors.success} /><Text className="flex-1 text-sm leading-5 text-ink">Exact price, stock and selected SKU are rechecked by the server before the bag is confirmed.</Text></View>
        {related.length ? <><Text className="mb-4 mt-9 text-xl font-black text-ink">You may also like</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{related.map(item => <View key={item.id} className="w-44"><ProductCard product={item} widthClass="w-full" saved={store.wishlist.includes(item.slug)} onToggleSaved={() => void store.toggleWishlist(item.slug)} onOpen={() => navigation.push("Product", { slug: item.slug })} /></View>)}</ScrollView></> : null}
      </View>
    </ScrollView>
    <SafeAreaView edges={["bottom"]} className="absolute bottom-0 left-0 right-0 border-t border-line bg-white px-4 pt-3" style={shadows.floating}><View className="flex-row gap-3"><Pressable accessibilityRole="button" accessibilityLabel="Wishlist" onPress={toggleSaved} className="h-[54px] w-[54px] items-center justify-center rounded-xl border border-line"><Heart size={23} color={colors.accent} fill={saved ? colors.accent : "transparent"} /></Pressable><View className="flex-1"><PrimaryButton label={added ? "ADDED · VIEW BAG" : variant ? "ADD TO BAG" : "SELECT SIZE"} loading={store.cartBusy} onPress={() => added ? navigation.navigate("MainTabs", { screen: "Bag" }) : void add()} /></View></View>{store.cartError ? <Text className="py-2 text-center text-xs text-sale">{store.cartError}</Text> : null}</SafeAreaView>
    <BottomSheetModal ref={sizeSheet} snapPoints={["55%"]} enablePanDownToClose><BottomSheetScrollView contentContainerStyle={{ padding: 20, paddingBottom: 40 }}><Text className="text-2xl font-black text-ink">Choose your size</Text><Text className="mt-1 text-sm text-muted">Available sizes for {color || "this colour"}.</Text><View className="mt-5 flex-row flex-wrap gap-3">{colorVariants.map(value => <VariantChoice key={value.id} value={`${value.size}${value.available > 0 ? "" : " · Sold out"}`} selected={variant?.id === value.id} disabled={value.available <= 0} onPress={() => { setVariant(value); sizeSheet.current?.dismiss(); }} />)}</View></BottomSheetScrollView></BottomSheetModal>
    <BottomSheetModal ref={fitSheet} snapPoints={["65%"]} enablePanDownToClose><BottomSheetScrollView contentContainerStyle={{ padding: 20, paddingBottom: 40 }}><Text className="text-2xl font-black text-ink">Find my size</Text><Text className="mt-2 text-sm leading-6 text-muted">Choose the size you usually wear. HIDI will map it only to an available SKU; this is guidance, not a body-measurement guarantee.</Text><View className="mt-6 gap-3">{Array.from(new Set(colorVariants.map(v => v.size))).map(size => <Pressable key={size} onPress={() => { const choice = colorVariants.find(v => v.size === size && v.available > 0); if (choice) setVariant(choice); fitSheet.current?.dismiss(); }} className="min-h-14 flex-row items-center justify-between rounded-xl border border-line px-4"><Text className="text-base font-extrabold text-ink">I usually wear {size}</Text><Text className="font-bold text-accent">USE {size}</Text></Pressable>)}</View><Text className="mt-6 text-xs leading-5 text-muted">Garment measurements, where supplied by the product catalogue, remain the best reference. Contact HIDI support before ordering if fit is uncertain.</Text></BottomSheetScrollView></BottomSheetModal>
  </View>;
}
