import React from "react";
import { Pressable, ScrollView, Text, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { ChevronRight, Crown, Heart, MapPin, Package, Settings, ShieldCheck, UserRound } from "lucide-react-native";
import { useCommerce } from "../store";
import { colors } from "../theme";
import { PrimaryButton } from "../components/Primitives";

function Row({ icon, title, detail, onPress }: { icon: React.ReactNode; title: string; detail?: string; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} className="min-h-16 flex-row items-center gap-4 border-b border-line py-3"><View className="h-10 w-10 items-center justify-center rounded-full bg-soft">{icon}</View><View className="flex-1"><Text className="font-extrabold text-ink">{title}</Text>{detail ? <Text className="mt-0.5 text-xs text-muted">{detail}</Text> : null}</View><ChevronRight size={19} color={colors.muted} /></Pressable>; }
export default function ProfileScreen() {
  const navigation = useNavigation<any>(); const store = useCommerce(); const name = String(store.auth?.user.user_metadata?.first_name ?? "");
  return <ScrollView className="flex-1 bg-white" contentContainerStyle={{ paddingBottom: 36 }}><View className="bg-ink px-5 pb-7 pt-7"><View className="h-16 w-16 items-center justify-center rounded-full bg-white/10"><UserRound size={30} color="white" /></View><Text className="mt-4 text-2xl font-black text-white">{store.auth ? (name ? `Hi, ${name}` : "Your HIDI") : "Welcome to HIDI"}</Text><Text className="mt-1 text-sm text-gray-300">{store.auth?.user.phone ?? "Sign in for orders, rewards and synced favourites."}</Text>{!store.auth ? <View className="mt-5"><PrimaryButton label="SIGN IN / JOIN" onPress={() => navigation.navigate("Login", { returnTo: "Profile" })} /></View> : <Pressable onPress={() => void store.setAuth(null)} className="mt-5 self-start rounded-lg border border-white/30 px-4 py-2"><Text className="font-bold text-white">SIGN OUT</Text></Pressable>}</View>
    <View className="px-5"><Row icon={<Package size={20} color={colors.ink} />} title="My orders" detail="Track, return and review" onPress={() => store.auth ? navigation.navigate("Orders") : navigation.navigate("Login", { returnTo: "Profile" })} /><Row icon={<Heart size={20} color={colors.accent} />} title="Wishlist" detail={`${store.wishlist.length} saved styles`} onPress={() => navigation.navigate("Wishlist")} /><Row icon={<MapPin size={20} color={colors.ink} />} title="Saved addresses" detail={`${store.addresses.length} addresses on this device`} onPress={() => navigation.navigate("CheckoutAddress")} /><Row icon={<Crown size={20} color={colors.gold} />} title="HIDI Insider" detail="Early access, points and member benefits" onPress={() => navigation.navigate("Insider")} /><Row icon={<ShieldCheck size={20} color={colors.success} />} title="Privacy & security" detail="Account access and consent controls" onPress={() => undefined} /><Row icon={<Settings size={20} color={colors.ink} />} title="App settings" detail="Notifications, appearance and help" onPress={() => undefined} /></View>
    <View className="mx-5 mt-8 rounded-card bg-pink-50 p-5"><Text className="text-lg font-black text-ink">Need help?</Text><Text className="mt-2 text-sm leading-6 text-muted">Visit the HIDI website support centre for current delivery, return and order policies.</Text><Pressable onPress={() => undefined} className="mt-4 self-start"><Text className="font-extrabold text-accent">CONTACT HIDI →</Text></Pressable></View>
  </ScrollView>;
}
