export const phase2Capabilities = {
  productDetail: "existing-api",
  gallery: "existing-media",
  variantAdd: "existing-api",
  garmentMeasurements: "existing-product-variant-fields",
  bodySizeChart: "unavailable",
  fitRecommendations: "unavailable",
  productCare: "existing-api-when-supplied",
  itemAwareDeliveryPromise: "partial-pin-serviceability-only",
  publicReviewAggregate: "existing-api",
  publicReviewDetail: "derived-from-review-list",
  reviewPhotosHelpfulReport: "unavailable",
  stockAlerts: "unavailable",
  relatedProducts: "existing-api",
  cartReadAddQuantityRemove: "existing-api",
  atomicCartVariantReplace: "unavailable",
  promotions: "unavailable",
  cartVersionQuoteVersion: "unavailable",
  savedForLater: "local-device-adaptation",
} as const;
