export const phase4Capabilities = {
  orderHistory: "existing-api",
  orderDetail: "existing-api",
  shipmentTracking: "partial-single-shipment-summary",
  splitShipments: "not-exposed-by-current-order-api",
  deliveryReschedule: "not-exposed-by-current-order-api",
  orderCancellation: "not-exposed-by-current-order-api",
  invoiceUrl: "not-exposed-by-current-order-api",
  returnEligibility: "existing-order-item-fields",
  returnRequest: "existing-api",
  evidenceUpload: "not-exposed-by-current-order-api",
  pickupOptions: "not-exposed-by-current-order-api",
  refundStatus: "existing-return-request-fields",
  exchangeRequest: "existing-api",
  exchangeQuote: "not-exposed-by-current-order-api",
  codRefundDestination: "not-exposed-by-current-order-api",
  reviewSubmission: "existing-api",
  guestOrderLookup: "deferred-to-phase5-H126",
} as const;
