export type HidiScreenPriority = "P0" | "P1";

export type HidiScreenContract = {
  id: `H${string}`;
  title: string;
  section: string;
  priority: HidiScreenPriority;
  phase: number;
};

export const screenRegistry: readonly HidiScreenContract[] = [
  { id: "H001", title: "Launch & restore", section: "Welcome & identity", priority: "P0", phase: 1 },
  { id: "H002", title: "Welcome", section: "Welcome & identity", priority: "P0", phase: 1 },
  { id: "H003", title: "Style preferences", section: "Welcome & identity", priority: "P0", phase: 1 },
  { id: "H004", title: "Sign in / join", section: "Welcome & identity", priority: "P0", phase: 1 },
  { id: "H005", title: "Verify phone", section: "Welcome & identity", priority: "P0", phase: 1 },
  { id: "H006", title: "Complete profile", section: "Welcome & identity", priority: "P0", phase: 1 },
  { id: "H007", title: "Consent preferences", section: "Welcome & identity", priority: "P0", phase: 1 },
  { id: "H008", title: "Verification limited", section: "Welcome & identity", priority: "P0", phase: 1 },
  { id: "H009", title: "Home", section: "Discover & save", priority: "P0", phase: 1 },
  { id: "H010", title: "Shop categories", section: "Discover & save", priority: "P0", phase: 1 },
  { id: "H011", title: "Collection landing", section: "Discover & save", priority: "P0", phase: 1 },
  { id: "H012", title: "Product listing", section: "Discover & save", priority: "P0", phase: 1 },
  { id: "H013", title: "Search entry", section: "Discover & save", priority: "P0", phase: 1 },
  { id: "H014", title: "Search suggestions", section: "Discover & save", priority: "P0", phase: 1 },
  { id: "H015", title: "Search results", section: "Discover & save", priority: "P0", phase: 1 },
  { id: "H016", title: "No search results", section: "Discover & save", priority: "P0", phase: 1 },
  { id: "H017", title: "Filter products", section: "Discover & save", priority: "P0", phase: 1 },
  { id: "H018", title: "Sort products", section: "Discover & save", priority: "P0", phase: 1 },
  { id: "H019", title: "Filtered listing", section: "Discover & save", priority: "P0", phase: 1 },
  { id: "H020", title: "Saved items", section: "Discover & save", priority: "P0", phase: 1 },
  { id: "H021", title: "Saved items empty", section: "Discover & save", priority: "P0", phase: 1 },
  { id: "H022", title: "Recently viewed", section: "Discover & save", priority: "P0", phase: 1 },
  { id: "H023", title: "Product detail", section: "Product confidence", priority: "P0", phase: 2 },
  { id: "H024", title: "Full-screen gallery", section: "Product confidence", priority: "P0", phase: 2 },
  { id: "H025", title: "Choose size & color", section: "Product confidence", priority: "P0", phase: 2 },
  { id: "H026", title: "Size guide", section: "Product confidence", priority: "P0", phase: 2 },
  { id: "H027", title: "Find my fit", section: "Product confidence", priority: "P0", phase: 2 },
  { id: "H028", title: "Details & care", section: "Product confidence", priority: "P0", phase: 2 },
  { id: "H029", title: "Check delivery", section: "Product confidence", priority: "P0", phase: 2 },
  { id: "H030", title: "Not delivered here", section: "Product confidence", priority: "P0", phase: 2 },
  { id: "H031", title: "Ratings & reviews", section: "Product confidence", priority: "P0", phase: 2 },
  { id: "H032", title: "Review detail & photos", section: "Product confidence", priority: "P0", phase: 2 },
  { id: "H033", title: "Back-in-stock alert", section: "Product confidence", priority: "P0", phase: 2 },
  { id: "H034", title: "Product unavailable", section: "Product confidence", priority: "P0", phase: 2 },
  { id: "H035", title: "Similar styles", section: "Product confidence", priority: "P0", phase: 2 },
  { id: "H036", title: "Added to bag", section: "Product confidence", priority: "P0", phase: 2 },
  { id: "H037", title: "Shopping bag", section: "Bag & promotions", priority: "P0", phase: 2 },
  { id: "H038", title: "Shopping bag empty", section: "Bag & promotions", priority: "P0", phase: 2 },
  { id: "H039", title: "Edit bag item", section: "Bag & promotions", priority: "P0", phase: 2 },
  { id: "H040", title: "Remove bag item", section: "Bag & promotions", priority: "P0", phase: 2 },
  { id: "H041", title: "Offers & promo code", section: "Bag & promotions", priority: "P0", phase: 2 },
  { id: "H042", title: "Promo code not applied", section: "Bag & promotions", priority: "P0", phase: 2 },
  { id: "H043", title: "Bag needs attention", section: "Bag & promotions", priority: "P0", phase: 2 },
  { id: "H044", title: "Saved for later", section: "Bag & promotions", priority: "P0", phase: 2 },
  { id: "H045", title: "Guest checkout contact", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H046", title: "Choose delivery address", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H047", title: "Add delivery address", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H048", title: "Address validation errors", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H049", title: "Address unavailable", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H050", title: "Delivery options", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H051", title: "Review order", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H052", title: "Payment methods", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H053", title: "UPI handoff", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H054", title: "Secure card checkout", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H055", title: "Cash on delivery", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H056", title: "Confirming payment", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H057", title: "Payment pending", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H058", title: "Payment not completed", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H059", title: "Order confirmed", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H060", title: "Resume checkout", section: "Checkout & payment", priority: "P0", phase: 3 },
  { id: "H061", title: "My orders", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H062", title: "Orders empty", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H063", title: "Order detail", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H064", title: "Track shipment", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H065", title: "Split shipments", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H066", title: "Delivery attempt failed", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H067", title: "Cancel order items", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H068", title: "Cancellation result", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H069", title: "Invoice / receipt", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H070", title: "Delivered order", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H071", title: "Select return items", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H072", title: "Return reason", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H073", title: "Return evidence", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H074", title: "Return pickup", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H075", title: "Review return", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H076", title: "Return tracking", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H077", title: "Refund in progress", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H078", title: "Refund completed", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H079", title: "Exchange size", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H080", title: "Exchange review", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H081", title: "Return unavailable", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H082", title: "Write a review", section: "Orders & after-sales", priority: "P0", phase: 4 },
  { id: "H083", title: "My HIDI", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H084", title: "Guest account", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H085", title: "Edit profile", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H086", title: "Manage addresses", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H087", title: "Saved payment methods", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H088", title: "Shopping preferences", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H089", title: "Notifications inbox", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H090", title: "Notifications empty", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H091", title: "Notification settings", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H092", title: "Help centre", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H093", title: "Help with an order", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H094", title: "Create support request", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H095", title: "Support conversation", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H096", title: "Contact HIDI", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H097", title: "Policies & legal", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H098", title: "Privacy choices", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H099", title: "Export my data", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H100", title: "Delete account", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H101", title: "Deletion requested", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H102", title: "Sign out", section: "Account & support", priority: "P0", phase: 5 },
  { id: "H103", title: "Loading skeleton", section: "Resilience & system states", priority: "P0", phase: 6 },
  { id: "H104", title: "Partial load failure", section: "Resilience & system states", priority: "P0", phase: 6 },
  { id: "H105", title: "Offline with saved content", section: "Resilience & system states", priority: "P0", phase: 6 },
  { id: "H106", title: "Offline without content", section: "Resilience & system states", priority: "P0", phase: 6 },
  { id: "H107", title: "Something went wrong", section: "Resilience & system states", priority: "P0", phase: 6 },
  { id: "H108", title: "Session expired", section: "Resilience & system states", priority: "P0", phase: 6 },
  { id: "H109", title: "Maintenance", section: "Resilience & system states", priority: "P0", phase: 6 },
  { id: "H110", title: "Required update", section: "Resilience & system states", priority: "P0", phase: 6 },
  { id: "H111", title: "Update available", section: "Resilience & system states", priority: "P0", phase: 6 },
  { id: "H112", title: "Permission explanation", section: "Resilience & system states", priority: "P0", phase: 6 },
  { id: "H113", title: "Permission declined", section: "Resilience & system states", priority: "P0", phase: 6 },
  { id: "H114", title: "Link no longer available", section: "Resilience & system states", priority: "P0", phase: 6 },
  { id: "H115", title: "Too many requests", section: "Resilience & system states", priority: "P0", phase: 6 },
  { id: "H116", title: "Attachment could not upload", section: "Resilience & system states", priority: "P0", phase: 6 },
  { id: "H117", title: "Editorial story", section: "Editorial & optional growth", priority: "P0", phase: 6 },
  { id: "H118", title: "Shop the look", section: "Editorial & optional growth", priority: "P0", phase: 6 },
  { id: "H119", title: "HIDI Circle / optional", section: "Editorial & optional growth", priority: "P1", phase: 7 },
  { id: "H120", title: "Invite a friend / optional", section: "Editorial & optional growth", priority: "P1", phase: 7 },
  { id: "H121", title: "Appearance settings", section: "Extended flows & confirmations", priority: "P0", phase: 6 },
  { id: "H122", title: "Home / dark appearance", section: "Extended flows & confirmations", priority: "P0", phase: 6 },
  { id: "H123", title: "Change phone number", section: "Extended flows & confirmations", priority: "P0", phase: 5 },
  { id: "H124", title: "Verify email address", section: "Extended flows & confirmations", priority: "P0", phase: 5 },
  { id: "H125", title: "Android permission dialog", section: "Extended flows & confirmations", priority: "P0", phase: 5 },
  { id: "H126", title: "Find a guest order", section: "Extended flows & confirmations", priority: "P0", phase: 5 },
  { id: "H127", title: "Gift note & packaging", section: "Extended flows & confirmations", priority: "P1", phase: 7 },
  { id: "H128", title: "COD refund destination", section: "Extended flows & confirmations", priority: "P0", phase: 4 },
  { id: "H129", title: "Return pickup missed", section: "Extended flows & confirmations", priority: "P0", phase: 4 },
  { id: "H130", title: "Exchange price difference", section: "Extended flows & confirmations", priority: "P0", phase: 4 },
  { id: "H131", title: "Refund needs attention", section: "Extended flows & confirmations", priority: "P0", phase: 4 },
  { id: "H132", title: "Support request received", section: "Extended flows & confirmations", priority: "P0", phase: 5 },
] as const;

export function screenContract(id: string) {
  return screenRegistry.find((screen) => screen.id === id);
}
