// Draft only. Business facts and operational disclosures require owner review.
export function initialDraft() {
  return {
    businessName: "High D Higher Dimensions",
    address: "",
    officerName: "",
    officerEmail: "",
    officerPhone: "",
    effectiveDate: "",
    sections: [
      { title: "Who we are", text: "HIDI is operated by {{businessName}}, at {{address}}. This policy explains how we handle information when you browse our website, use an account, shop, contact us or choose to receive updates." },
      { title: "Information we collect", text: "Account information includes your mobile number, account identifier, any name or email you provide, and sign-in and verification records. Shopping information includes products, sizes, cart and wishlist records, orders, recipient details, delivery addresses, PIN codes and contact details. Returns, refunds and rewards can generate records linked to an order or account.\n\nPayment information includes the reference, amount, status and transaction metadata received from our payment provider. Payment instrument details entered in the provider's interface are handled by that provider. Please do not send payment passwords, card security codes or OTPs to support.\n\nCommunications include enquiries, support correspondence, reviews, attachments you choose to provide, and subscription preferences. Technical information can include IP addresses, device and browser information, access and error records, and identifiers used for sign-in or shopping sessions." },
      { title: "Why we use information", text: "We use information to provide account access, maintain shopping sessions, process and fulfil orders, check delivery availability, arrange payment and refunds, manage rewards, answer enquiries and display reviews you submit for publication. We also use relevant records to prevent misuse, investigate disputes, secure services and meet legal record-keeping requirements.\n\nYou may choose not to supply information or ask to withdraw permission for its use. We may be unable to provide a service that needs it, such as delivery without an address. Withdrawal does not remove records we must retain under applicable law." },
      { title: "Service providers and disclosure", text: "We share relevant information with providers carrying out the requested service. These include Microsoft Azure for hosting, database and media; Cloudflare for delivery and security; MSG91 and Firebase for authentication or SMS when used; Razorpay for payments; and Delhivery or the courier assigned to an order. Messaging platforms can process information needed for their services.\n\nWe may disclose information where required by law, to respond to a valid legal request, investigate fraud or protect legal rights. Providers may process information in their operating locations; transfers must meet applicable legal requirements." },
      { title: "Device storage and optional tracking", text: "Browser storage and session identifiers support sign-in, cart and wishlist access. Clearing or blocking storage can affect these features.\n\n[Add the approved optional tracking disclosure and available controls, or confirm that no optional tracking is active.]" },
      { title: "Marketing choices", text: "To stop optional promotional communication, contact {{officerEmail}}. Available account preferences and messaging opt-out instructions may offer additional controls. Necessary sign-in and existing-order messages are separate from promotional updates. Stopping marketing does not cancel an order." },
      { title: "Retention and security", text: "We retain information for the purposes described here and for legal obligations, fraud prevention and disputes.\n\n[Add approved retention periods or criteria for account, order, support, marketing and technical records, including legal exceptions.]\n\nOur safeguards include encrypted website connections, access controls and account verification. No system guarantees complete security. Keep your OTP private and sign out on shared devices." },
      { title: "Requests and privacy concerns", text: "For information, correction, deletion, withdrawal or a privacy concern, contact our privacy/grievance officer {{officerName}} at {{officerEmail}}, {{officerPhone}}, or {{address}}. We may ask for proportionate identity verification. Do not send unnecessary sensitive documents.\n\nWe will assess your request and explain information that must be retained or services affected by withdrawal. Privacy grievances will be handled within the period required by applicable law." },
      { title: "Children and policy updates", text: "Purchases must be managed by someone legally able to contract. If you are under 18, ask a parent or lawful guardian to manage purchases. Contact HIDI before submitting a child's information. An OTP does not establish age or verified parental consent.\n\nWe will update this policy as our practices or requirements change. Updates show a version and effective date; earlier approved versions are retained." },
    ],
  };
}
