import type { NavigatorScreenParams } from "@react-navigation/native";
import type { Filters, SortKey } from "../data/catalog";
import type { AddressFieldErrors, CheckoutAddress } from "../models/checkout";

export type RootStackParamList = {
  Launch: undefined;
  Welcome: undefined;
  StylePreferences: undefined;
  SignIn: { returnTo?: string } | undefined;
  VerifyPhone: { phone: string; resendAfterSeconds: number; returnTo?: string };
  CompleteProfile: { returnTo?: string } | undefined;
  ConsentPreferences: undefined;
  VerificationLimited: { phone?: string; retryUntil: number };
  MainTabs: NavigatorScreenParams<RootTabParamList> | undefined;
  Collection: { slug: string; title: string };
  Listing: { title: string; collectionSlug?: string; categorySlug?: string; query?: string; filters?: Filters; sort?: SortKey };
  Search: undefined;
  SearchResults: { query: string; filters?: Filters; sort?: SortKey };
  Filters: { title: string; productsSource: "listing" | "search"; query?: string; collectionSlug?: string; categorySlug?: string; current: Filters; sort?: SortKey };
  RecentlyViewed: undefined;
  ProductDeferred: { slug: string; queryId?: string; selectedVariantId?: string };
  ProductGallery: { slug: string; initialIndex?: number };
  VariantPicker: { slug: string; selectedVariantId?: string; savedForLaterKey?: string };
  SizeGuide: { slug: string; selectedVariantId?: string };
  FitHelper: { slug: string; selectedVariantId?: string };
  DetailsCare: { slug: string };
  DeliveryCheck: { slug: string; variantId: string };
  Reviews: { slug: string };
  ReviewDetail: { slug: string; reviewId: string };
  StockAlert: { slug: string; variantId: string };
  ProductUnavailable: { slug: string };
  SimilarStyles: { slug: string };
  AddedToBag: { slug: string; variantId: string; quantity: number; reconciled: boolean; savedCleanupFailed?: boolean };
  BagEdit: { lineId: string };
  BagRemove: { lineId: string };
  Promotions: undefined;
  PromoFailure: { code: string };
  BagAttention: undefined;
  SavedForLater: undefined;
  CheckoutContact: undefined;
  CheckoutAddress: undefined;
  AddAddress: undefined;
  AddressErrors: { errors: AddressFieldErrors; draft: CheckoutAddress };
  AddressUnavailable: { pin: string };
  DeliveryOptions: undefined;
  ReviewOrder: undefined;
  PaymentMethods: undefined;
  UpiHandoff: undefined;
  SecureCardCheckout: undefined;
  CashOnDelivery: undefined;
  ConfirmingPayment: { orderNumber: string };
  PaymentPending: { orderNumber: string; reason?: string };
  PaymentFailed: { orderNumber: string; reason: string };
  OrderConfirmed: { orderNumber: string };
  ResumeCheckout: undefined;
};

export type RootTabParamList = {
  Home: undefined;
  Shop: undefined;
  Saved: undefined;
  Bag: undefined;
  You: undefined;
};
