import type { NavigatorScreenParams } from "@react-navigation/native";
import type { Filters, SortKey } from "../data/catalog";
import type { AddressFieldErrors, CheckoutAddress } from "../models/checkout";
import type { AfterSalesDraft, AfterSalesType } from "../models/order";

export type RootStackParamList = {
  Launch: undefined;
  Welcome: undefined;
  StylePreferences: undefined;
  SignIn: { returnTo?: string } | undefined;
  VerifyPhone: { phone: string; resendAfterSeconds: number; returnTo?: string };
  CompleteProfile: { returnTo?: string } | undefined;
  ConsentPreferences: undefined;
  VerificationLimited: { phone?: string; retryUntil: number };
  MainTabs: NavigatorScreenParams<RootTabParamList> | undefined;
  Collection: { slug: string; title: string };
  Listing: { title: string; collectionSlug?: string; categorySlug?: string; query?: string; filters?: Filters; sort?: SortKey };
  Search: undefined;
  SearchResults: { query: string; filters?: Filters; sort?: SortKey };
  Filters: { title: string; productsSource: "listing" | "search"; query?: string; collectionSlug?: string; categorySlug?: string; current: Filters; sort?: SortKey };
  RecentlyViewed: undefined;
  ProductDeferred: { slug: string; queryId?: string; selectedVariantId?: string };
  ProductGallery: { slug: string; initialIndex?: number };
  VariantPicker: { slug: string; selectedVariantId?: string; savedForLaterKey?: string };
  SizeGuide: { slug: string; selectedVariantId?: string };
  FitHelper: { slug: string; selectedVariantId?: string };
  DetailsCare: { slug: string };
  DeliveryCheck: { slug: string; variantId: string };
  Reviews: { slug: string };
  ReviewDetail: { slug: string; reviewId: string };
  StockAlert: { slug: string; variantId: string };
  ProductUnavailable: { slug: string };
  SimilarStyles: { slug: string };
  AddedToBag: { slug: string; variantId: string; quantity: number; reconciled: boolean; savedCleanupFailed?: boolean };
  BagEdit: { lineId: string };
  BagRemove: { lineId: string };
  Promotions: undefined;
  PromoFailure: { code: string };
  BagAttention: undefined;
  SavedForLater: undefined;
  CheckoutContact: undefined;
  CheckoutAddress: undefined;
  AddAddress: undefined;
  AddressErrors: { errors: AddressFieldErrors; draft: CheckoutAddress };
  AddressUnavailable: { pin: string };
  DeliveryOptions: undefined;
  ReviewOrder: undefined;
  PaymentMethods: undefined;
  UpiHandoff: undefined;
  SecureCardCheckout: undefined;
  CashOnDelivery: undefined;
  ConfirmingPayment: { orderNumber: string };
  PaymentPending: { orderNumber: string; reason?: string };
  PaymentFailed: { orderNumber: string; reason: string };
  OrderConfirmed: { orderNumber: string };
  ResumeCheckout: undefined;
  MyOrders: undefined;
  OrderDetail: { orderNumber: string };
  TrackShipment: { orderNumber: string };
  SplitShipments: { orderNumber: string };
  DeliveryAttemptFailed: { orderNumber: string };
  CancelOrderItems: { orderNumber: string };
  CancellationResult: { orderNumber: string; status: string; message?: string };
  InvoiceReceipt: { orderNumber: string };
  DeliveredOrder: { orderNumber: string };
  SelectReturnItems: { orderNumber: string; mode?: AfterSalesType };
  ReturnReason: { orderNumber: string; orderItemId: string; quantity: number; type: AfterSalesType };
  ReturnEvidence: { draft: AfterSalesDraft };
  ReturnPickup: { draft: AfterSalesDraft };
  ReviewReturn: { draft: AfterSalesDraft };
  ReturnTracking: { orderNumber: string; requestId: string };
  RefundInProgress: { orderNumber: string; requestId: string };
  RefundCompleted: { orderNumber: string; requestId: string };
  ExchangeSize: { orderNumber: string; orderItemId: string; quantity: number };
  ExchangeReview: { orderNumber: string; orderItemId: string; quantity: number; requestedSize: string };
  ReturnUnavailable: { orderNumber: string; reason: string };
  WriteReview: { orderNumber: string; orderItemId: string };
  CodRefundDestination: { orderNumber?: string; draft?: AfterSalesDraft } | undefined;
  ReturnPickupMissed: { orderNumber: string; requestId: string };
  ExchangePriceDifference: { orderNumber: string; orderItemId: string; requestedSize: string };
  RefundNeedsAttention: { orderNumber: string; requestId?: string };
};

export type RootTabParamList = {
  Home: undefined;
  Shop: undefined;
  Saved: undefined;
  Bag: undefined;
  You: undefined;
};
